package com.stephen.core.model.base;

import java.util.List;

import com.stephen.core.model.Channel;
import com.stephen.core.model.ChannelAttr;
import com.stephen.core.model.ChannelCount;
import com.stephen.core.model.ChannelExt;
import com.stephen.core.model.ChannelTxt;
import com.stephen.core.model.Content;

public class BaseChannel {
	protected static final String INDEX = "/index.html";

	@Override
	public String toString() {
		return "BaseChannel [channelId=" + channelId + ", modelId=" + modelId + ", siteId=" + siteId + ", parentId="
				+ parentId + ", channelPath=" + channelPath + ", lft=" + lft + ", rgt=" + rgt + ", priority=" + priority
				+ ", hasContent=" + hasContent + ", isDisplay=" + isDisplay + "]";
	}

	private ChannelExt channelExt;
	private ChannelCount channelCount;
	private ChannelTxt channelTxt;
	private List<ChannelAttr> channelAttr;
	private List<Content> content;
	private List<Channel> child;
	private Channel parent;

	public void setParent(Channel parent) {
		this.parent = parent;
	}

	public Channel getParent() {
		return parent;
	}

	public List<Channel> getChild() {
		return child;
	}

	public void setChild(List<Channel> childs) {
		this.child = childs;
	}

	public List<Content> getContent() {
		return content;
	}

	public void setContent(List<Content> content) {
		this.content = content;
	}

	public List<ChannelAttr> getChannelAttr() {
		return channelAttr;
	}

	public ChannelCount getChannelCount() {
		return channelCount;
	}

	public ChannelExt getChannelExt() {
		return channelExt;
	}

	public ChannelTxt getChannelTxt() {
		return channelTxt;
	}

	public void setChannelAttr(List<ChannelAttr> channelAttrs) {
		this.channelAttr = channelAttrs;
	}

	public void setChannelCount(ChannelCount channelCount) {
		this.channelCount = channelCount;
	}

	public void setChannelExt(ChannelExt channelExt) {
		this.channelExt = channelExt;
	}

	public void setChannelTxt(ChannelTxt channelTxt) {
		this.channelTxt = channelTxt;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_channel.channel_id
	 * 
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	private Integer channelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_channel.model_id
	 * 
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	private Integer modelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_channel.site_id
	 * 
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	private Integer siteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_channel.parent_id
	 * 
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	private Integer parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_channel.channel_path
	 * 
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	private String channelPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_channel.lft
	 * 
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	private Integer lft;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_channel.rgt
	 * 
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	private Integer rgt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_channel.priority
	 * 
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	private Integer priority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_channel.has_content
	 * 
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	private Boolean hasContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_channel.is_display
	 * 
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	private Boolean isDisplay;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_channel.channel_id
	 * 
	 * @return the value of s_channel.channel_id
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public Integer getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_channel.channel_id
	 * 
	 * @param channelId
	 *            the value for s_channel.channel_id
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_channel.model_id
	 * 
	 * @return the value of s_channel.model_id
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public Integer getModelId() {
		return modelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_channel.model_id
	 * 
	 * @param modelId
	 *            the value for s_channel.model_id
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public void setModelId(Integer modelId) {
		this.modelId = modelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_channel.site_id
	 * 
	 * @return the value of s_channel.site_id
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public Integer getSiteId() {
		return siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_channel.site_id
	 * 
	 * @param siteId
	 *            the value for s_channel.site_id
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_channel.parent_id
	 * 
	 * @return the value of s_channel.parent_id
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_channel.parent_id
	 * 
	 * @param parentId
	 *            the value for s_channel.parent_id
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_channel.channel_path
	 * 
	 * @return the value of s_channel.channel_path
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public String getChannelPath() {
		return channelPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_channel.channel_path
	 * 
	 * @param channelPath
	 *            the value for s_channel.channel_path
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public void setChannelPath(String channelPath) {
		this.channelPath = channelPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_channel.lft
	 * 
	 * @return the value of s_channel.lft
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public Integer getLft() {
		return lft;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_channel.lft
	 * 
	 * @param lft
	 *            the value for s_channel.lft
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public void setLft(Integer lft) {
		this.lft = lft;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_channel.rgt
	 * 
	 * @return the value of s_channel.rgt
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public Integer getRgt() {
		return rgt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_channel.rgt
	 * 
	 * @param rgt
	 *            the value for s_channel.rgt
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public void setRgt(Integer rgt) {
		this.rgt = rgt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_channel.priority
	 * 
	 * @return the value of s_channel.priority
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public Integer getPriority() {
		return priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_channel.priority
	 * 
	 * @param priority
	 *            the value for s_channel.priority
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_channel.has_content
	 * 
	 * @return the value of s_channel.has_content
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public Boolean getHasContent() {
		return hasContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_channel.has_content
	 * 
	 * @param hasContent
	 *            the value for s_channel.has_content
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public void setHasContent(Boolean hasContent) {
		this.hasContent = hasContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_channel.is_display
	 * 
	 * @return the value of s_channel.is_display
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public Boolean getIsDisplay() {
		return isDisplay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_channel.is_display
	 * 
	 * @param isDisplay
	 *            the value for s_channel.is_display
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	public void setIsDisplay(Boolean isDisplay) {
		this.isDisplay = isDisplay;
	}
}