package com.stephen.core.model.base;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.stephen.core.model.Channel;
import com.stephen.core.model.ContentAttr;
import com.stephen.core.model.ContentExt;

public class BaseContent {
	private Channel channel;

	public Channel getChannel() {
		return channel;
	}

	public void setChannel(Channel channel) {
		this.channel = channel;
	}

	private ContentExt contentExt;
	private List<ContentAttr> contentAttr;
	private Map<String, String> attr = new HashMap<>();

	public Map<String, String> getAttr() {
		if (attr.size() == 0) {
			for (ContentAttr a : contentAttr) {
				attr.put(a.getAttrName(), a.getAttrValue());
			}
		}
		return attr;
	}

	public void setAttr(Map<String, String> attr) {
		this.attr = attr;
	}

	public List<ContentAttr> getContentAttr() {
		return contentAttr;
	}

	public void setContentAttr(List<ContentAttr> contentAttr) {
		this.contentAttr = contentAttr;
	}

	public ContentExt getContentExt() {
		return contentExt;
	}

	public void setContentExt(ContentExt contentExt) {
		this.contentExt = contentExt;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_content.content_id
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	private Integer contentId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_content.channel_id
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	private Integer channelId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_content.user_id
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_content.type_id
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	private Integer typeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_content.model_id
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	private Integer modelId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_content.site_id
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	private Integer siteId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_content.sort_date
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	private Date sortDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_content.top_level
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	private Byte topLevel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_content.has_title_img
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	private Boolean hasTitleImg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_content.is_recommend
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	private Boolean isRecommend;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_content.status
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	private Byte status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_content.views_day
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	private Integer viewsDay;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_content.comments_day
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	private Short commentsDay;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_content.downloads_day
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	private Short downloadsDay;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_content.ups_day
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	private Short upsDay;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column s_content.score
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	private Integer score;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_content.content_id
	 *
	 * @return the value of s_content.content_id
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public Integer getContentId() {
		return contentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_content.content_id
	 *
	 * @param contentId
	 *            the value for s_content.content_id
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public void setContentId(Integer contentId) {
		this.contentId = contentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_content.channel_id
	 *
	 * @return the value of s_content.channel_id
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public Integer getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_content.channel_id
	 *
	 * @param channelId
	 *            the value for s_content.channel_id
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_content.user_id
	 *
	 * @return the value of s_content.user_id
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_content.user_id
	 *
	 * @param userId
	 *            the value for s_content.user_id
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_content.type_id
	 *
	 * @return the value of s_content.type_id
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public Integer getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_content.type_id
	 *
	 * @param typeId
	 *            the value for s_content.type_id
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_content.model_id
	 *
	 * @return the value of s_content.model_id
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public Integer getModelId() {
		return modelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_content.model_id
	 *
	 * @param modelId
	 *            the value for s_content.model_id
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public void setModelId(Integer modelId) {
		this.modelId = modelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_content.site_id
	 *
	 * @return the value of s_content.site_id
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public Integer getSiteId() {
		return siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_content.site_id
	 *
	 * @param siteId
	 *            the value for s_content.site_id
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_content.sort_date
	 *
	 * @return the value of s_content.sort_date
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public Date getSortDate() {
		return sortDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_content.sort_date
	 *
	 * @param sortDate
	 *            the value for s_content.sort_date
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public void setSortDate(Date sortDate) {
		this.sortDate = sortDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_content.top_level
	 *
	 * @return the value of s_content.top_level
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public Byte getTopLevel() {
		return topLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_content.top_level
	 *
	 * @param topLevel
	 *            the value for s_content.top_level
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public void setTopLevel(Byte topLevel) {
		this.topLevel = topLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_content.has_title_img
	 *
	 * @return the value of s_content.has_title_img
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public Boolean getHasTitleImg() {
		return hasTitleImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_content.has_title_img
	 *
	 * @param hasTitleImg
	 *            the value for s_content.has_title_img
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public void setHasTitleImg(Boolean hasTitleImg) {
		this.hasTitleImg = hasTitleImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_content.is_recommend
	 *
	 * @return the value of s_content.is_recommend
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public Boolean getIsRecommend() {
		return isRecommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_content.is_recommend
	 *
	 * @param isRecommend
	 *            the value for s_content.is_recommend
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public void setIsRecommend(Boolean isRecommend) {
		this.isRecommend = isRecommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_content.status
	 *
	 * @return the value of s_content.status
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_content.status
	 *
	 * @param status
	 *            the value for s_content.status
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_content.views_day
	 *
	 * @return the value of s_content.views_day
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public Integer getViewsDay() {
		return viewsDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_content.views_day
	 *
	 * @param viewsDay
	 *            the value for s_content.views_day
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public void setViewsDay(Integer viewsDay) {
		this.viewsDay = viewsDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_content.comments_day
	 *
	 * @return the value of s_content.comments_day
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public Short getCommentsDay() {
		return commentsDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_content.comments_day
	 *
	 * @param commentsDay
	 *            the value for s_content.comments_day
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public void setCommentsDay(Short commentsDay) {
		this.commentsDay = commentsDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_content.downloads_day
	 *
	 * @return the value of s_content.downloads_day
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public Short getDownloadsDay() {
		return downloadsDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_content.downloads_day
	 *
	 * @param downloadsDay
	 *            the value for s_content.downloads_day
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public void setDownloadsDay(Short downloadsDay) {
		this.downloadsDay = downloadsDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_content.ups_day
	 *
	 * @return the value of s_content.ups_day
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public Short getUpsDay() {
		return upsDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_content.ups_day
	 *
	 * @param upsDay
	 *            the value for s_content.ups_day
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public void setUpsDay(Short upsDay) {
		this.upsDay = upsDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column s_content.score
	 *
	 * @return the value of s_content.score
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column s_content.score
	 *
	 * @param score
	 *            the value for s_content.score
	 *
	 * @mbggenerated Tue Jan 10 20:04:17 CST 2017
	 */
	public void setScore(Integer score) {
		this.score = score;
	}
}