package com.stephen.core.model;

import java.util.Date;

public class Authentication {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_authentication.authentication_id
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    private String authenticationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_authentication.userid
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_authentication.username
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_authentication.email
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_authentication.login_time
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_authentication.login_ip
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    private String loginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_authentication.update_time
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_authentication.authentication_id
     *
     * @return the value of s_authentication.authentication_id
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    public String getAuthenticationId() {
        return authenticationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_authentication.authentication_id
     *
     * @param authenticationId the value for s_authentication.authentication_id
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    public void setAuthenticationId(String authenticationId) {
        this.authenticationId = authenticationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_authentication.userid
     *
     * @return the value of s_authentication.userid
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_authentication.userid
     *
     * @param userid the value for s_authentication.userid
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_authentication.username
     *
     * @return the value of s_authentication.username
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_authentication.username
     *
     * @param username the value for s_authentication.username
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_authentication.email
     *
     * @return the value of s_authentication.email
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_authentication.email
     *
     * @param email the value for s_authentication.email
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_authentication.login_time
     *
     * @return the value of s_authentication.login_time
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_authentication.login_time
     *
     * @param loginTime the value for s_authentication.login_time
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_authentication.login_ip
     *
     * @return the value of s_authentication.login_ip
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_authentication.login_ip
     *
     * @param loginIp the value for s_authentication.login_ip
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_authentication.update_time
     *
     * @return the value of s_authentication.update_time
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_authentication.update_time
     *
     * @param updateTime the value for s_authentication.update_time
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}