package com.stephen.core.model;

public class ChannelAttr {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_attr.channel_id
	 * @mbggenerated  Wed Feb 15 22:49:38 CST 2017
	 */
	private Integer channelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_attr.attr_name
	 * @mbggenerated  Wed Feb 15 22:49:38 CST 2017
	 */
	private String attrName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_attr.attr_value
	 * @mbggenerated  Wed Feb 15 22:49:38 CST 2017
	 */
	private String attrValue;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_attr.channel_id
	 * @return  the value of s_channel_attr.channel_id
	 * @mbggenerated  Wed Feb 15 22:49:38 CST 2017
	 */
	public Integer getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_attr.channel_id
	 * @param channelId  the value for s_channel_attr.channel_id
	 * @mbggenerated  Wed Feb 15 22:49:38 CST 2017
	 */
	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_attr.attr_name
	 * @return  the value of s_channel_attr.attr_name
	 * @mbggenerated  Wed Feb 15 22:49:38 CST 2017
	 */
	public String getAttrName() {
		return attrName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_attr.attr_name
	 * @param attrName  the value for s_channel_attr.attr_name
	 * @mbggenerated  Wed Feb 15 22:49:38 CST 2017
	 */
	public void setAttrName(String attrName) {
		this.attrName = attrName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_attr.attr_value
	 * @return  the value of s_channel_attr.attr_value
	 * @mbggenerated  Wed Feb 15 22:49:38 CST 2017
	 */
	public String getAttrValue() {
		return attrValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_attr.attr_value
	 * @param attrValue  the value for s_channel_attr.attr_value
	 * @mbggenerated  Wed Feb 15 22:49:38 CST 2017
	 */
	public void setAttrValue(String attrValue) {
		this.attrValue = attrValue;
	}
}