package com.stephen.core.model;

public class ChannelCount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_count.channel_id
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	private Integer channelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_count.views
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	private Integer views;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_count.views_month
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	private Integer viewsMonth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_count.views_week
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	private Integer viewsWeek;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_count.views_day
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	private Integer viewsDay;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_count.channel_id
	 * @return  the value of s_channel_count.channel_id
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	public Integer getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_count.channel_id
	 * @param channelId  the value for s_channel_count.channel_id
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_count.views
	 * @return  the value of s_channel_count.views
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	public Integer getViews() {
		return views;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_count.views
	 * @param views  the value for s_channel_count.views
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	public void setViews(Integer views) {
		this.views = views;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_count.views_month
	 * @return  the value of s_channel_count.views_month
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	public Integer getViewsMonth() {
		return viewsMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_count.views_month
	 * @param viewsMonth  the value for s_channel_count.views_month
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	public void setViewsMonth(Integer viewsMonth) {
		this.viewsMonth = viewsMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_count.views_week
	 * @return  the value of s_channel_count.views_week
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	public Integer getViewsWeek() {
		return viewsWeek;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_count.views_week
	 * @param viewsWeek  the value for s_channel_count.views_week
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	public void setViewsWeek(Integer viewsWeek) {
		this.viewsWeek = viewsWeek;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_count.views_day
	 * @return  the value of s_channel_count.views_day
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	public Integer getViewsDay() {
		return viewsDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_count.views_day
	 * @param viewsDay  the value for s_channel_count.views_day
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	public void setViewsDay(Integer viewsDay) {
		this.viewsDay = viewsDay;
	}
}