package com.stephen.core.model;

public class ChannelTxt {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_txt.channel_id
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	private Integer channelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_txt.txt
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	private String txt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_txt.txt1
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	private String txt1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_txt.txt2
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	private String txt2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_txt.txt3
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	private String txt3;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_txt.channel_id
	 * @return  the value of s_channel_txt.channel_id
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	public Integer getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_txt.channel_id
	 * @param channelId  the value for s_channel_txt.channel_id
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_txt.txt
	 * @return  the value of s_channel_txt.txt
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	public String getTxt() {
		return txt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_txt.txt
	 * @param txt  the value for s_channel_txt.txt
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	public void setTxt(String txt) {
		this.txt = txt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_txt.txt1
	 * @return  the value of s_channel_txt.txt1
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	public String getTxt1() {
		return txt1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_txt.txt1
	 * @param txt1  the value for s_channel_txt.txt1
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	public void setTxt1(String txt1) {
		this.txt1 = txt1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_txt.txt2
	 * @return  the value of s_channel_txt.txt2
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	public String getTxt2() {
		return txt2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_txt.txt2
	 * @param txt2  the value for s_channel_txt.txt2
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	public void setTxt2(String txt2) {
		this.txt2 = txt2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_txt.txt3
	 * @return  the value of s_channel_txt.txt3
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	public String getTxt3() {
		return txt3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_txt.txt3
	 * @param txt3  the value for s_channel_txt.txt3
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	public void setTxt3(String txt3) {
		this.txt3 = txt3;
	}
}