package com.stephen.core.model;

public class ChannelExt {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.channel_id
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private Integer channelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.channel_name
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private String channelName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.final_step
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private Byte finalStep;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.after_check
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private Byte afterCheck;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.is_static_channel
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private String isStaticChannel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.is_static_content
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private String isStaticContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.is_access_by_dir
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private String isAccessByDir;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.is_list_child
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private String isListChild;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.page_size
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private Integer pageSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.channel_rule
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private String channelRule;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.content_rule
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private String contentRule;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.link
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private String link;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.tpl_channel
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private String tplChannel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.tpl_content
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private String tplContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.title_img
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private String titleImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.content_img
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private String contentImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.has_title_img
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private Boolean hasTitleImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.has_content_img
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private Boolean hasContentImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.title_img_width
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private Integer titleImgWidth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.title_img_height
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private Integer titleImgHeight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.content_img_width
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private Integer contentImgWidth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.content_img_height
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private Integer contentImgHeight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.comment_control
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private Integer commentControl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.allow_updown
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private Boolean allowUpdown;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.is_blank
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private Boolean isBlank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.title
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.keywords
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private String keywords;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.description
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.allow_share
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private Boolean allowShare;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_channel_ext.allow_score
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	private Boolean allowScore;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.channel_id
	 * @return  the value of s_channel_ext.channel_id
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public Integer getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.channel_id
	 * @param channelId  the value for s_channel_ext.channel_id
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.channel_name
	 * @return  the value of s_channel_ext.channel_name
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public String getChannelName() {
		return channelName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.channel_name
	 * @param channelName  the value for s_channel_ext.channel_name
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.final_step
	 * @return  the value of s_channel_ext.final_step
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public Byte getFinalStep() {
		return finalStep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.final_step
	 * @param finalStep  the value for s_channel_ext.final_step
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setFinalStep(Byte finalStep) {
		this.finalStep = finalStep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.after_check
	 * @return  the value of s_channel_ext.after_check
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public Byte getAfterCheck() {
		return afterCheck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.after_check
	 * @param afterCheck  the value for s_channel_ext.after_check
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setAfterCheck(Byte afterCheck) {
		this.afterCheck = afterCheck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.is_static_channel
	 * @return  the value of s_channel_ext.is_static_channel
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public String getIsStaticChannel() {
		return isStaticChannel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.is_static_channel
	 * @param isStaticChannel  the value for s_channel_ext.is_static_channel
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setIsStaticChannel(String isStaticChannel) {
		this.isStaticChannel = isStaticChannel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.is_static_content
	 * @return  the value of s_channel_ext.is_static_content
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public String getIsStaticContent() {
		return isStaticContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.is_static_content
	 * @param isStaticContent  the value for s_channel_ext.is_static_content
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setIsStaticContent(String isStaticContent) {
		this.isStaticContent = isStaticContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.is_access_by_dir
	 * @return  the value of s_channel_ext.is_access_by_dir
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public String getIsAccessByDir() {
		return isAccessByDir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.is_access_by_dir
	 * @param isAccessByDir  the value for s_channel_ext.is_access_by_dir
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setIsAccessByDir(String isAccessByDir) {
		this.isAccessByDir = isAccessByDir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.is_list_child
	 * @return  the value of s_channel_ext.is_list_child
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public String getIsListChild() {
		return isListChild;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.is_list_child
	 * @param isListChild  the value for s_channel_ext.is_list_child
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setIsListChild(String isListChild) {
		this.isListChild = isListChild;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.page_size
	 * @return  the value of s_channel_ext.page_size
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public Integer getPageSize() {
		return pageSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.page_size
	 * @param pageSize  the value for s_channel_ext.page_size
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.channel_rule
	 * @return  the value of s_channel_ext.channel_rule
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public String getChannelRule() {
		return channelRule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.channel_rule
	 * @param channelRule  the value for s_channel_ext.channel_rule
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setChannelRule(String channelRule) {
		this.channelRule = channelRule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.content_rule
	 * @return  the value of s_channel_ext.content_rule
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public String getContentRule() {
		return contentRule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.content_rule
	 * @param contentRule  the value for s_channel_ext.content_rule
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setContentRule(String contentRule) {
		this.contentRule = contentRule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.link
	 * @return  the value of s_channel_ext.link
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.link
	 * @param link  the value for s_channel_ext.link
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setLink(String link) {
		this.link = link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.tpl_channel
	 * @return  the value of s_channel_ext.tpl_channel
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public String getTplChannel() {
		return tplChannel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.tpl_channel
	 * @param tplChannel  the value for s_channel_ext.tpl_channel
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setTplChannel(String tplChannel) {
		this.tplChannel = tplChannel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.tpl_content
	 * @return  the value of s_channel_ext.tpl_content
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public String getTplContent() {
		return tplContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.tpl_content
	 * @param tplContent  the value for s_channel_ext.tpl_content
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setTplContent(String tplContent) {
		this.tplContent = tplContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.title_img
	 * @return  the value of s_channel_ext.title_img
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public String getTitleImg() {
		return titleImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.title_img
	 * @param titleImg  the value for s_channel_ext.title_img
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setTitleImg(String titleImg) {
		this.titleImg = titleImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.content_img
	 * @return  the value of s_channel_ext.content_img
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public String getContentImg() {
		return contentImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.content_img
	 * @param contentImg  the value for s_channel_ext.content_img
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setContentImg(String contentImg) {
		this.contentImg = contentImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.has_title_img
	 * @return  the value of s_channel_ext.has_title_img
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public Boolean getHasTitleImg() {
		return hasTitleImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.has_title_img
	 * @param hasTitleImg  the value for s_channel_ext.has_title_img
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setHasTitleImg(Boolean hasTitleImg) {
		this.hasTitleImg = hasTitleImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.has_content_img
	 * @return  the value of s_channel_ext.has_content_img
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public Boolean getHasContentImg() {
		return hasContentImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.has_content_img
	 * @param hasContentImg  the value for s_channel_ext.has_content_img
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setHasContentImg(Boolean hasContentImg) {
		this.hasContentImg = hasContentImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.title_img_width
	 * @return  the value of s_channel_ext.title_img_width
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public Integer getTitleImgWidth() {
		return titleImgWidth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.title_img_width
	 * @param titleImgWidth  the value for s_channel_ext.title_img_width
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setTitleImgWidth(Integer titleImgWidth) {
		this.titleImgWidth = titleImgWidth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.title_img_height
	 * @return  the value of s_channel_ext.title_img_height
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public Integer getTitleImgHeight() {
		return titleImgHeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.title_img_height
	 * @param titleImgHeight  the value for s_channel_ext.title_img_height
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setTitleImgHeight(Integer titleImgHeight) {
		this.titleImgHeight = titleImgHeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.content_img_width
	 * @return  the value of s_channel_ext.content_img_width
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public Integer getContentImgWidth() {
		return contentImgWidth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.content_img_width
	 * @param contentImgWidth  the value for s_channel_ext.content_img_width
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setContentImgWidth(Integer contentImgWidth) {
		this.contentImgWidth = contentImgWidth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.content_img_height
	 * @return  the value of s_channel_ext.content_img_height
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public Integer getContentImgHeight() {
		return contentImgHeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.content_img_height
	 * @param contentImgHeight  the value for s_channel_ext.content_img_height
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setContentImgHeight(Integer contentImgHeight) {
		this.contentImgHeight = contentImgHeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.comment_control
	 * @return  the value of s_channel_ext.comment_control
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public Integer getCommentControl() {
		return commentControl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.comment_control
	 * @param commentControl  the value for s_channel_ext.comment_control
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setCommentControl(Integer commentControl) {
		this.commentControl = commentControl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.allow_updown
	 * @return  the value of s_channel_ext.allow_updown
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public Boolean getAllowUpdown() {
		return allowUpdown;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.allow_updown
	 * @param allowUpdown  the value for s_channel_ext.allow_updown
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setAllowUpdown(Boolean allowUpdown) {
		this.allowUpdown = allowUpdown;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.is_blank
	 * @return  the value of s_channel_ext.is_blank
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public Boolean getIsBlank() {
		return isBlank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.is_blank
	 * @param isBlank  the value for s_channel_ext.is_blank
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setIsBlank(Boolean isBlank) {
		this.isBlank = isBlank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.title
	 * @return  the value of s_channel_ext.title
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.title
	 * @param title  the value for s_channel_ext.title
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.keywords
	 * @return  the value of s_channel_ext.keywords
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public String getKeywords() {
		return keywords;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.keywords
	 * @param keywords  the value for s_channel_ext.keywords
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.description
	 * @return  the value of s_channel_ext.description
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.description
	 * @param description  the value for s_channel_ext.description
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.allow_share
	 * @return  the value of s_channel_ext.allow_share
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public Boolean getAllowShare() {
		return allowShare;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.allow_share
	 * @param allowShare  the value for s_channel_ext.allow_share
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setAllowShare(Boolean allowShare) {
		this.allowShare = allowShare;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_channel_ext.allow_score
	 * @return  the value of s_channel_ext.allow_score
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public Boolean getAllowScore() {
		return allowScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_channel_ext.allow_score
	 * @param allowScore  the value for s_channel_ext.allow_score
	 * @mbggenerated  Wed Feb 15 22:50:05 CST 2017
	 */
	public void setAllowScore(Boolean allowScore) {
		this.allowScore = allowScore;
	}
}