package com.stephen.core.model;

public class ChannelUserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_channel_user.channel_id
     *
     * @mbggenerated Tue Jan 10 20:00:28 CST 2017
     */
    private Integer channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_channel_user.user_id
     *
     * @mbggenerated Tue Jan 10 20:00:28 CST 2017
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_channel_user.channel_id
     *
     * @return the value of s_channel_user.channel_id
     *
     * @mbggenerated Tue Jan 10 20:00:28 CST 2017
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_channel_user.channel_id
     *
     * @param channelId the value for s_channel_user.channel_id
     *
     * @mbggenerated Tue Jan 10 20:00:28 CST 2017
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_channel_user.user_id
     *
     * @return the value of s_channel_user.user_id
     *
     * @mbggenerated Tue Jan 10 20:00:28 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_channel_user.user_id
     *
     * @param userId the value for s_channel_user.user_id
     *
     * @mbggenerated Tue Jan 10 20:00:28 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}