package com.stephen.core.model;

public class ChnlGroupContriKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_chnl_group_contri.channel_id
     *
     * @mbggenerated Tue Jan 10 20:01:59 CST 2017
     */
    private Integer channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_chnl_group_contri.group_id
     *
     * @mbggenerated Tue Jan 10 20:01:59 CST 2017
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_chnl_group_contri.channel_id
     *
     * @return the value of s_chnl_group_contri.channel_id
     *
     * @mbggenerated Tue Jan 10 20:01:59 CST 2017
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_chnl_group_contri.channel_id
     *
     * @param channelId the value for s_chnl_group_contri.channel_id
     *
     * @mbggenerated Tue Jan 10 20:01:59 CST 2017
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_chnl_group_contri.group_id
     *
     * @return the value of s_chnl_group_contri.group_id
     *
     * @mbggenerated Tue Jan 10 20:01:59 CST 2017
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_chnl_group_contri.group_id
     *
     * @param groupId the value for s_chnl_group_contri.group_id
     *
     * @mbggenerated Tue Jan 10 20:01:59 CST 2017
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}