package com.stephen.core.model;

import java.util.Date;

public class CmsUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_user.user_id
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_user.username
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_user.email
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_user.password
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_user.register_time
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_user.register_ip
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    private String registerIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_user.last_login_time
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_user.last_login_ip
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    private String lastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_user.login_count
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    private Integer loginCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_user.reset_key
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    private String resetKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_user.reset_pwd
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    private String resetPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_user.error_time
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    private Date errorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_user.error_count
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    private Integer errorCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_user.error_ip
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    private String errorIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_user.activation
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    private Boolean activation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_user.activation_code
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    private String activationCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_user.user_id
     *
     * @return the value of so_user.user_id
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_user.user_id
     *
     * @param userId the value for so_user.user_id
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_user.username
     *
     * @return the value of so_user.username
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_user.username
     *
     * @param username the value for so_user.username
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_user.email
     *
     * @return the value of so_user.email
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_user.email
     *
     * @param email the value for so_user.email
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_user.password
     *
     * @return the value of so_user.password
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_user.password
     *
     * @param password the value for so_user.password
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_user.register_time
     *
     * @return the value of so_user.register_time
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_user.register_time
     *
     * @param registerTime the value for so_user.register_time
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_user.register_ip
     *
     * @return the value of so_user.register_ip
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public String getRegisterIp() {
        return registerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_user.register_ip
     *
     * @param registerIp the value for so_user.register_ip
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public void setRegisterIp(String registerIp) {
        this.registerIp = registerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_user.last_login_time
     *
     * @return the value of so_user.last_login_time
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_user.last_login_time
     *
     * @param lastLoginTime the value for so_user.last_login_time
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_user.last_login_ip
     *
     * @return the value of so_user.last_login_ip
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_user.last_login_ip
     *
     * @param lastLoginIp the value for so_user.last_login_ip
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_user.login_count
     *
     * @return the value of so_user.login_count
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_user.login_count
     *
     * @param loginCount the value for so_user.login_count
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_user.reset_key
     *
     * @return the value of so_user.reset_key
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public String getResetKey() {
        return resetKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_user.reset_key
     *
     * @param resetKey the value for so_user.reset_key
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public void setResetKey(String resetKey) {
        this.resetKey = resetKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_user.reset_pwd
     *
     * @return the value of so_user.reset_pwd
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public String getResetPwd() {
        return resetPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_user.reset_pwd
     *
     * @param resetPwd the value for so_user.reset_pwd
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public void setResetPwd(String resetPwd) {
        this.resetPwd = resetPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_user.error_time
     *
     * @return the value of so_user.error_time
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public Date getErrorTime() {
        return errorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_user.error_time
     *
     * @param errorTime the value for so_user.error_time
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public void setErrorTime(Date errorTime) {
        this.errorTime = errorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_user.error_count
     *
     * @return the value of so_user.error_count
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public Integer getErrorCount() {
        return errorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_user.error_count
     *
     * @param errorCount the value for so_user.error_count
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public void setErrorCount(Integer errorCount) {
        this.errorCount = errorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_user.error_ip
     *
     * @return the value of so_user.error_ip
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public String getErrorIp() {
        return errorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_user.error_ip
     *
     * @param errorIp the value for so_user.error_ip
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public void setErrorIp(String errorIp) {
        this.errorIp = errorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_user.activation
     *
     * @return the value of so_user.activation
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public Boolean getActivation() {
        return activation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_user.activation
     *
     * @param activation the value for so_user.activation
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public void setActivation(Boolean activation) {
        this.activation = activation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_user.activation_code
     *
     * @return the value of so_user.activation_code
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public String getActivationCode() {
        return activationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_user.activation_code
     *
     * @param activationCode the value for so_user.activation_code
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    public void setActivationCode(String activationCode) {
        this.activationCode = activationCode;
    }
}