package com.stephen.core.model;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_comment.comment_id
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_comment.comment_user_id
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    private Integer commentUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_comment.reply_user_id
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    private Integer replyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_comment.content_id
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    private Integer contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_comment.site_id
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    private Integer siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_comment.create_time
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_comment.reply_time
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    private Date replyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_comment.ups
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    private Short ups;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_comment.downs
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    private Short downs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_comment.is_recommend
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    private Boolean isRecommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_comment.is_checked
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    private Boolean isChecked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_comment.score
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_comment.comment_id
     *
     * @return the value of s_comment.comment_id
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_comment.comment_id
     *
     * @param commentId the value for s_comment.comment_id
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_comment.comment_user_id
     *
     * @return the value of s_comment.comment_user_id
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public Integer getCommentUserId() {
        return commentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_comment.comment_user_id
     *
     * @param commentUserId the value for s_comment.comment_user_id
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public void setCommentUserId(Integer commentUserId) {
        this.commentUserId = commentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_comment.reply_user_id
     *
     * @return the value of s_comment.reply_user_id
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public Integer getReplyUserId() {
        return replyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_comment.reply_user_id
     *
     * @param replyUserId the value for s_comment.reply_user_id
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public void setReplyUserId(Integer replyUserId) {
        this.replyUserId = replyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_comment.content_id
     *
     * @return the value of s_comment.content_id
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_comment.content_id
     *
     * @param contentId the value for s_comment.content_id
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_comment.site_id
     *
     * @return the value of s_comment.site_id
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_comment.site_id
     *
     * @param siteId the value for s_comment.site_id
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_comment.create_time
     *
     * @return the value of s_comment.create_time
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_comment.create_time
     *
     * @param createTime the value for s_comment.create_time
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_comment.reply_time
     *
     * @return the value of s_comment.reply_time
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public Date getReplyTime() {
        return replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_comment.reply_time
     *
     * @param replyTime the value for s_comment.reply_time
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public void setReplyTime(Date replyTime) {
        this.replyTime = replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_comment.ups
     *
     * @return the value of s_comment.ups
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public Short getUps() {
        return ups;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_comment.ups
     *
     * @param ups the value for s_comment.ups
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public void setUps(Short ups) {
        this.ups = ups;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_comment.downs
     *
     * @return the value of s_comment.downs
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public Short getDowns() {
        return downs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_comment.downs
     *
     * @param downs the value for s_comment.downs
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public void setDowns(Short downs) {
        this.downs = downs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_comment.is_recommend
     *
     * @return the value of s_comment.is_recommend
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public Boolean getIsRecommend() {
        return isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_comment.is_recommend
     *
     * @param isRecommend the value for s_comment.is_recommend
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public void setIsRecommend(Boolean isRecommend) {
        this.isRecommend = isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_comment.is_checked
     *
     * @return the value of s_comment.is_checked
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public Boolean getIsChecked() {
        return isChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_comment.is_checked
     *
     * @param isChecked the value for s_comment.is_checked
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public void setIsChecked(Boolean isChecked) {
        this.isChecked = isChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_comment.score
     *
     * @return the value of s_comment.score
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_comment.score
     *
     * @param score the value for s_comment.score
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}