package com.stephen.core.model;

public class CommentExtWithBLOBs extends CommentExt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_comment_ext.text
     *
     * @mbggenerated Tue Jan 10 20:02:54 CST 2017
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_comment_ext.reply
     *
     * @mbggenerated Tue Jan 10 20:02:54 CST 2017
     */
    private String reply;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_comment_ext.text
     *
     * @return the value of s_comment_ext.text
     *
     * @mbggenerated Tue Jan 10 20:02:54 CST 2017
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_comment_ext.text
     *
     * @param text the value for s_comment_ext.text
     *
     * @mbggenerated Tue Jan 10 20:02:54 CST 2017
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_comment_ext.reply
     *
     * @return the value of s_comment_ext.reply
     *
     * @mbggenerated Tue Jan 10 20:02:54 CST 2017
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_comment_ext.reply
     *
     * @param reply the value for s_comment_ext.reply
     *
     * @mbggenerated Tue Jan 10 20:02:54 CST 2017
     */
    public void setReply(String reply) {
        this.reply = reply;
    }
}