package com.stephen.core.model;

public class CommentExt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_comment_ext.comment_id
     *
     * @mbggenerated Tue Jan 10 20:02:54 CST 2017
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_comment_ext.ip
     *
     * @mbggenerated Tue Jan 10 20:02:54 CST 2017
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_comment_ext.comment_id
     *
     * @return the value of s_comment_ext.comment_id
     *
     * @mbggenerated Tue Jan 10 20:02:54 CST 2017
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_comment_ext.comment_id
     *
     * @param commentId the value for s_comment_ext.comment_id
     *
     * @mbggenerated Tue Jan 10 20:02:54 CST 2017
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_comment_ext.ip
     *
     * @return the value of s_comment_ext.ip
     *
     * @mbggenerated Tue Jan 10 20:02:54 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_comment_ext.ip
     *
     * @param ip the value for s_comment_ext.ip
     *
     * @mbggenerated Tue Jan 10 20:02:54 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip;
    }
}