package com.stephen.core.model;

public class ContentTopicKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_topic.content_id
     *
     * @mbggenerated Tue Jan 10 20:06:57 CST 2017
     */
    private Integer contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_topic.topic_id
     *
     * @mbggenerated Tue Jan 10 20:06:57 CST 2017
     */
    private Integer topicId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_topic.content_id
     *
     * @return the value of s_content_topic.content_id
     *
     * @mbggenerated Tue Jan 10 20:06:57 CST 2017
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_topic.content_id
     *
     * @param contentId the value for s_content_topic.content_id
     *
     * @mbggenerated Tue Jan 10 20:06:57 CST 2017
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_topic.topic_id
     *
     * @return the value of s_content_topic.topic_id
     *
     * @mbggenerated Tue Jan 10 20:06:57 CST 2017
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_topic.topic_id
     *
     * @param topicId the value for s_content_topic.topic_id
     *
     * @mbggenerated Tue Jan 10 20:06:57 CST 2017
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }
}