package com.stephen.core.model;

import java.util.Date;

public class ContentExt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_ext.content_id
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    private Integer contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_ext.title
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_ext.short_title
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    private String shortTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_ext.author
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_ext.origin
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_ext.origin_url
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    private String originUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_ext.description
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_ext.release_date
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    private Date releaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_ext.media_path
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    private String mediaPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_ext.media_type
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    private String mediaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_ext.title_color
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    private String titleColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_ext.is_bold
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    private Boolean isBold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_ext.title_img
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    private String titleImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_ext.content_img
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    private String contentImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_ext.type_img
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    private String typeImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_ext.link
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_ext.tpl_content
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    private String tplContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_ext.need_regenerate
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    private Boolean needRegenerate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_ext.content_id
     *
     * @return the value of s_content_ext.content_id
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_ext.content_id
     *
     * @param contentId the value for s_content_ext.content_id
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_ext.title
     *
     * @return the value of s_content_ext.title
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_ext.title
     *
     * @param title the value for s_content_ext.title
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_ext.short_title
     *
     * @return the value of s_content_ext.short_title
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public String getShortTitle() {
        return shortTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_ext.short_title
     *
     * @param shortTitle the value for s_content_ext.short_title
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public void setShortTitle(String shortTitle) {
        this.shortTitle = shortTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_ext.author
     *
     * @return the value of s_content_ext.author
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_ext.author
     *
     * @param author the value for s_content_ext.author
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_ext.origin
     *
     * @return the value of s_content_ext.origin
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_ext.origin
     *
     * @param origin the value for s_content_ext.origin
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public void setOrigin(String origin) {
        this.origin = origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_ext.origin_url
     *
     * @return the value of s_content_ext.origin_url
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public String getOriginUrl() {
        return originUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_ext.origin_url
     *
     * @param originUrl the value for s_content_ext.origin_url
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public void setOriginUrl(String originUrl) {
        this.originUrl = originUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_ext.description
     *
     * @return the value of s_content_ext.description
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_ext.description
     *
     * @param description the value for s_content_ext.description
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_ext.release_date
     *
     * @return the value of s_content_ext.release_date
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_ext.release_date
     *
     * @param releaseDate the value for s_content_ext.release_date
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_ext.media_path
     *
     * @return the value of s_content_ext.media_path
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public String getMediaPath() {
        return mediaPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_ext.media_path
     *
     * @param mediaPath the value for s_content_ext.media_path
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public void setMediaPath(String mediaPath) {
        this.mediaPath = mediaPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_ext.media_type
     *
     * @return the value of s_content_ext.media_type
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public String getMediaType() {
        return mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_ext.media_type
     *
     * @param mediaType the value for s_content_ext.media_type
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public void setMediaType(String mediaType) {
        this.mediaType = mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_ext.title_color
     *
     * @return the value of s_content_ext.title_color
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public String getTitleColor() {
        return titleColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_ext.title_color
     *
     * @param titleColor the value for s_content_ext.title_color
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public void setTitleColor(String titleColor) {
        this.titleColor = titleColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_ext.is_bold
     *
     * @return the value of s_content_ext.is_bold
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public Boolean getIsBold() {
        return isBold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_ext.is_bold
     *
     * @param isBold the value for s_content_ext.is_bold
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public void setIsBold(Boolean isBold) {
        this.isBold = isBold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_ext.title_img
     *
     * @return the value of s_content_ext.title_img
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public String getTitleImg() {
        return titleImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_ext.title_img
     *
     * @param titleImg the value for s_content_ext.title_img
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public void setTitleImg(String titleImg) {
        this.titleImg = titleImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_ext.content_img
     *
     * @return the value of s_content_ext.content_img
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public String getContentImg() {
        return contentImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_ext.content_img
     *
     * @param contentImg the value for s_content_ext.content_img
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public void setContentImg(String contentImg) {
        this.contentImg = contentImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_ext.type_img
     *
     * @return the value of s_content_ext.type_img
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public String getTypeImg() {
        return typeImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_ext.type_img
     *
     * @param typeImg the value for s_content_ext.type_img
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public void setTypeImg(String typeImg) {
        this.typeImg = typeImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_ext.link
     *
     * @return the value of s_content_ext.link
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_ext.link
     *
     * @param link the value for s_content_ext.link
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_ext.tpl_content
     *
     * @return the value of s_content_ext.tpl_content
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public String getTplContent() {
        return tplContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_ext.tpl_content
     *
     * @param tplContent the value for s_content_ext.tpl_content
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public void setTplContent(String tplContent) {
        this.tplContent = tplContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_ext.need_regenerate
     *
     * @return the value of s_content_ext.need_regenerate
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public Boolean getNeedRegenerate() {
        return needRegenerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_ext.need_regenerate
     *
     * @param needRegenerate the value for s_content_ext.need_regenerate
     *
     * @mbggenerated Tue Jan 10 20:05:45 CST 2017
     */
    public void setNeedRegenerate(Boolean needRegenerate) {
        this.needRegenerate = needRegenerate;
    }
}