package com.stephen.core.model;

public class ContentCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_count.content_id
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    private Integer contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_count.views
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    private Integer views;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_count.views_month
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    private Integer viewsMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_count.views_week
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    private Integer viewsWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_count.views_day
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    private Integer viewsDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_count.comments
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    private Integer comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_count.comments_month
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    private Integer commentsMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_count.comments_week
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    private Short commentsWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_count.comments_day
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    private Short commentsDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_count.downloads
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    private Integer downloads;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_count.downloads_month
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    private Integer downloadsMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_count.downloads_week
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    private Short downloadsWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_count.downloads_day
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    private Short downloadsDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_count.ups
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    private Integer ups;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_count.ups_month
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    private Integer upsMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_count.ups_week
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    private Short upsWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_count.ups_day
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    private Short upsDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_count.downs
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    private Integer downs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_count.content_id
     *
     * @return the value of s_content_count.content_id
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_count.content_id
     *
     * @param contentId the value for s_content_count.content_id
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_count.views
     *
     * @return the value of s_content_count.views
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public Integer getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_count.views
     *
     * @param views the value for s_content_count.views
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public void setViews(Integer views) {
        this.views = views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_count.views_month
     *
     * @return the value of s_content_count.views_month
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public Integer getViewsMonth() {
        return viewsMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_count.views_month
     *
     * @param viewsMonth the value for s_content_count.views_month
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public void setViewsMonth(Integer viewsMonth) {
        this.viewsMonth = viewsMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_count.views_week
     *
     * @return the value of s_content_count.views_week
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public Integer getViewsWeek() {
        return viewsWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_count.views_week
     *
     * @param viewsWeek the value for s_content_count.views_week
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public void setViewsWeek(Integer viewsWeek) {
        this.viewsWeek = viewsWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_count.views_day
     *
     * @return the value of s_content_count.views_day
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public Integer getViewsDay() {
        return viewsDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_count.views_day
     *
     * @param viewsDay the value for s_content_count.views_day
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public void setViewsDay(Integer viewsDay) {
        this.viewsDay = viewsDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_count.comments
     *
     * @return the value of s_content_count.comments
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public Integer getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_count.comments
     *
     * @param comments the value for s_content_count.comments
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public void setComments(Integer comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_count.comments_month
     *
     * @return the value of s_content_count.comments_month
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public Integer getCommentsMonth() {
        return commentsMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_count.comments_month
     *
     * @param commentsMonth the value for s_content_count.comments_month
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public void setCommentsMonth(Integer commentsMonth) {
        this.commentsMonth = commentsMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_count.comments_week
     *
     * @return the value of s_content_count.comments_week
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public Short getCommentsWeek() {
        return commentsWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_count.comments_week
     *
     * @param commentsWeek the value for s_content_count.comments_week
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public void setCommentsWeek(Short commentsWeek) {
        this.commentsWeek = commentsWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_count.comments_day
     *
     * @return the value of s_content_count.comments_day
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public Short getCommentsDay() {
        return commentsDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_count.comments_day
     *
     * @param commentsDay the value for s_content_count.comments_day
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public void setCommentsDay(Short commentsDay) {
        this.commentsDay = commentsDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_count.downloads
     *
     * @return the value of s_content_count.downloads
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public Integer getDownloads() {
        return downloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_count.downloads
     *
     * @param downloads the value for s_content_count.downloads
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public void setDownloads(Integer downloads) {
        this.downloads = downloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_count.downloads_month
     *
     * @return the value of s_content_count.downloads_month
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public Integer getDownloadsMonth() {
        return downloadsMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_count.downloads_month
     *
     * @param downloadsMonth the value for s_content_count.downloads_month
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public void setDownloadsMonth(Integer downloadsMonth) {
        this.downloadsMonth = downloadsMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_count.downloads_week
     *
     * @return the value of s_content_count.downloads_week
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public Short getDownloadsWeek() {
        return downloadsWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_count.downloads_week
     *
     * @param downloadsWeek the value for s_content_count.downloads_week
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public void setDownloadsWeek(Short downloadsWeek) {
        this.downloadsWeek = downloadsWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_count.downloads_day
     *
     * @return the value of s_content_count.downloads_day
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public Short getDownloadsDay() {
        return downloadsDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_count.downloads_day
     *
     * @param downloadsDay the value for s_content_count.downloads_day
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public void setDownloadsDay(Short downloadsDay) {
        this.downloadsDay = downloadsDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_count.ups
     *
     * @return the value of s_content_count.ups
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public Integer getUps() {
        return ups;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_count.ups
     *
     * @param ups the value for s_content_count.ups
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public void setUps(Integer ups) {
        this.ups = ups;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_count.ups_month
     *
     * @return the value of s_content_count.ups_month
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public Integer getUpsMonth() {
        return upsMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_count.ups_month
     *
     * @param upsMonth the value for s_content_count.ups_month
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public void setUpsMonth(Integer upsMonth) {
        this.upsMonth = upsMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_count.ups_week
     *
     * @return the value of s_content_count.ups_week
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public Short getUpsWeek() {
        return upsWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_count.ups_week
     *
     * @param upsWeek the value for s_content_count.ups_week
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public void setUpsWeek(Short upsWeek) {
        this.upsWeek = upsWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_count.ups_day
     *
     * @return the value of s_content_count.ups_day
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public Short getUpsDay() {
        return upsDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_count.ups_day
     *
     * @param upsDay the value for s_content_count.ups_day
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public void setUpsDay(Short upsDay) {
        this.upsDay = upsDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_count.downs
     *
     * @return the value of s_content_count.downs
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public Integer getDowns() {
        return downs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_count.downs
     *
     * @param downs the value for s_content_count.downs
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    public void setDowns(Integer downs) {
        this.downs = downs;
    }
}