package com.stephen.core.model;

public class ContentPictureKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_picture.content_id
     *
     * @mbggenerated Tue Jan 10 20:06:39 CST 2017
     */
    private Integer contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_picture.priority
     *
     * @mbggenerated Tue Jan 10 20:06:39 CST 2017
     */
    private Integer priority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_picture.content_id
     *
     * @return the value of s_content_picture.content_id
     *
     * @mbggenerated Tue Jan 10 20:06:39 CST 2017
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_picture.content_id
     *
     * @param contentId the value for s_content_picture.content_id
     *
     * @mbggenerated Tue Jan 10 20:06:39 CST 2017
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_picture.priority
     *
     * @return the value of s_content_picture.priority
     *
     * @mbggenerated Tue Jan 10 20:06:39 CST 2017
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_picture.priority
     *
     * @param priority the value for s_content_picture.priority
     *
     * @mbggenerated Tue Jan 10 20:06:39 CST 2017
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
}