package com.stephen.core.model;

import java.util.Date;

public class ContentCheck {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_check.content_id
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    private Integer contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_check.check_step
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    private Byte checkStep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_check.check_opinion
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    private String checkOpinion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_check.is_rejected
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    private Boolean isRejected;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_check.reviewer
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    private Integer reviewer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_check.check_date
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    private Date checkDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_check.content_id
     *
     * @return the value of s_content_check.content_id
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_check.content_id
     *
     * @param contentId the value for s_content_check.content_id
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_check.check_step
     *
     * @return the value of s_content_check.check_step
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    public Byte getCheckStep() {
        return checkStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_check.check_step
     *
     * @param checkStep the value for s_content_check.check_step
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    public void setCheckStep(Byte checkStep) {
        this.checkStep = checkStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_check.check_opinion
     *
     * @return the value of s_content_check.check_opinion
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    public String getCheckOpinion() {
        return checkOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_check.check_opinion
     *
     * @param checkOpinion the value for s_content_check.check_opinion
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    public void setCheckOpinion(String checkOpinion) {
        this.checkOpinion = checkOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_check.is_rejected
     *
     * @return the value of s_content_check.is_rejected
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    public Boolean getIsRejected() {
        return isRejected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_check.is_rejected
     *
     * @param isRejected the value for s_content_check.is_rejected
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    public void setIsRejected(Boolean isRejected) {
        this.isRejected = isRejected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_check.reviewer
     *
     * @return the value of s_content_check.reviewer
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    public Integer getReviewer() {
        return reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_check.reviewer
     *
     * @param reviewer the value for s_content_check.reviewer
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    public void setReviewer(Integer reviewer) {
        this.reviewer = reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_check.check_date
     *
     * @return the value of s_content_check.check_date
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    public Date getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_check.check_date
     *
     * @param checkDate the value for s_content_check.check_date
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }
}