package com.stephen.core.model;

public class ContentTxt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_txt.content_id
     *
     * @mbggenerated Tue Jan 10 20:07:11 CST 2017
     */
    private Integer contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_txt.txt
     *
     * @mbggenerated Tue Jan 10 20:07:11 CST 2017
     */
    private String txt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_txt.txt1
     *
     * @mbggenerated Tue Jan 10 20:07:11 CST 2017
     */
    private String txt1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_txt.txt2
     *
     * @mbggenerated Tue Jan 10 20:07:11 CST 2017
     */
    private String txt2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_txt.txt3
     *
     * @mbggenerated Tue Jan 10 20:07:11 CST 2017
     */
    private String txt3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_txt.content_id
     *
     * @return the value of s_content_txt.content_id
     *
     * @mbggenerated Tue Jan 10 20:07:11 CST 2017
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_txt.content_id
     *
     * @param contentId the value for s_content_txt.content_id
     *
     * @mbggenerated Tue Jan 10 20:07:11 CST 2017
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_txt.txt
     *
     * @return the value of s_content_txt.txt
     *
     * @mbggenerated Tue Jan 10 20:07:11 CST 2017
     */
    public String getTxt() {
        return txt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_txt.txt
     *
     * @param txt the value for s_content_txt.txt
     *
     * @mbggenerated Tue Jan 10 20:07:11 CST 2017
     */
    public void setTxt(String txt) {
        this.txt = txt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_txt.txt1
     *
     * @return the value of s_content_txt.txt1
     *
     * @mbggenerated Tue Jan 10 20:07:11 CST 2017
     */
    public String getTxt1() {
        return txt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_txt.txt1
     *
     * @param txt1 the value for s_content_txt.txt1
     *
     * @mbggenerated Tue Jan 10 20:07:11 CST 2017
     */
    public void setTxt1(String txt1) {
        this.txt1 = txt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_txt.txt2
     *
     * @return the value of s_content_txt.txt2
     *
     * @mbggenerated Tue Jan 10 20:07:11 CST 2017
     */
    public String getTxt2() {
        return txt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_txt.txt2
     *
     * @param txt2 the value for s_content_txt.txt2
     *
     * @mbggenerated Tue Jan 10 20:07:11 CST 2017
     */
    public void setTxt2(String txt2) {
        this.txt2 = txt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_txt.txt3
     *
     * @return the value of s_content_txt.txt3
     *
     * @mbggenerated Tue Jan 10 20:07:11 CST 2017
     */
    public String getTxt3() {
        return txt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_txt.txt3
     *
     * @param txt3 the value for s_content_txt.txt3
     *
     * @mbggenerated Tue Jan 10 20:07:11 CST 2017
     */
    public void setTxt3(String txt3) {
        this.txt3 = txt3;
    }
}