package com.stephen.core.model;

public class ContentAttachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_attachment.content_id
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    private Integer contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_attachment.priority
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_attachment.attachment_path
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    private String attachmentPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_attachment.attachment_name
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    private String attachmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_attachment.filename
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_attachment.download_count
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    private Integer downloadCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_attachment.content_id
     *
     * @return the value of s_content_attachment.content_id
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_attachment.content_id
     *
     * @param contentId the value for s_content_attachment.content_id
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_attachment.priority
     *
     * @return the value of s_content_attachment.priority
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_attachment.priority
     *
     * @param priority the value for s_content_attachment.priority
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_attachment.attachment_path
     *
     * @return the value of s_content_attachment.attachment_path
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    public String getAttachmentPath() {
        return attachmentPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_attachment.attachment_path
     *
     * @param attachmentPath the value for s_content_attachment.attachment_path
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    public void setAttachmentPath(String attachmentPath) {
        this.attachmentPath = attachmentPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_attachment.attachment_name
     *
     * @return the value of s_content_attachment.attachment_name
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    public String getAttachmentName() {
        return attachmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_attachment.attachment_name
     *
     * @param attachmentName the value for s_content_attachment.attachment_name
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    public void setAttachmentName(String attachmentName) {
        this.attachmentName = attachmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_attachment.filename
     *
     * @return the value of s_content_attachment.filename
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_attachment.filename
     *
     * @param filename the value for s_content_attachment.filename
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_attachment.download_count
     *
     * @return the value of s_content_attachment.download_count
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    public Integer getDownloadCount() {
        return downloadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_attachment.download_count
     *
     * @param downloadCount the value for s_content_attachment.download_count
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    public void setDownloadCount(Integer downloadCount) {
        this.downloadCount = downloadCount;
    }
}