package com.stephen.core.model;

public class ContentAttr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_attr.content_id
     *
     * @mbggenerated Tue Jan 10 20:04:55 CST 2017
     */
    private Integer contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_attr.attr_name
     *
     * @mbggenerated Tue Jan 10 20:04:55 CST 2017
     */
    private String attrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_attr.attr_value
     *
     * @mbggenerated Tue Jan 10 20:04:55 CST 2017
     */
    private String attrValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_attr.content_id
     *
     * @return the value of s_content_attr.content_id
     *
     * @mbggenerated Tue Jan 10 20:04:55 CST 2017
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_attr.content_id
     *
     * @param contentId the value for s_content_attr.content_id
     *
     * @mbggenerated Tue Jan 10 20:04:55 CST 2017
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_attr.attr_name
     *
     * @return the value of s_content_attr.attr_name
     *
     * @mbggenerated Tue Jan 10 20:04:55 CST 2017
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_attr.attr_name
     *
     * @param attrName the value for s_content_attr.attr_name
     *
     * @mbggenerated Tue Jan 10 20:04:55 CST 2017
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_attr.attr_value
     *
     * @return the value of s_content_attr.attr_value
     *
     * @mbggenerated Tue Jan 10 20:04:55 CST 2017
     */
    public String getAttrValue() {
        return attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_attr.attr_value
     *
     * @param attrValue the value for s_content_attr.attr_value
     *
     * @mbggenerated Tue Jan 10 20:04:55 CST 2017
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue;
    }
}