package com.stephen.core.model;

public class ContentGroupViewKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_group_view.content_id
     *
     * @mbggenerated Tue Jan 10 20:06:13 CST 2017
     */
    private Integer contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_group_view.group_id
     *
     * @mbggenerated Tue Jan 10 20:06:13 CST 2017
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_group_view.content_id
     *
     * @return the value of s_content_group_view.content_id
     *
     * @mbggenerated Tue Jan 10 20:06:13 CST 2017
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_group_view.content_id
     *
     * @param contentId the value for s_content_group_view.content_id
     *
     * @mbggenerated Tue Jan 10 20:06:13 CST 2017
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_group_view.group_id
     *
     * @return the value of s_content_group_view.group_id
     *
     * @mbggenerated Tue Jan 10 20:06:13 CST 2017
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_group_view.group_id
     *
     * @param groupId the value for s_content_group_view.group_id
     *
     * @mbggenerated Tue Jan 10 20:06:13 CST 2017
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}