package com.stephen.core.model;

public class ContentChannelKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_channel.channel_id
     *
     * @mbggenerated Wed Feb 15 22:53:04 CST 2017
     */
    private Integer channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_content_channel.content_id
     *
     * @mbggenerated Wed Feb 15 22:53:04 CST 2017
     */
    private Integer contentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_channel.channel_id
     *
     * @return the value of s_content_channel.channel_id
     *
     * @mbggenerated Wed Feb 15 22:53:04 CST 2017
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_channel.channel_id
     *
     * @param channelId the value for s_content_channel.channel_id
     *
     * @mbggenerated Wed Feb 15 22:53:04 CST 2017
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_content_channel.content_id
     *
     * @return the value of s_content_channel.content_id
     *
     * @mbggenerated Wed Feb 15 22:53:04 CST 2017
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_content_channel.content_id
     *
     * @param contentId the value for s_content_channel.content_id
     *
     * @mbggenerated Wed Feb 15 22:53:04 CST 2017
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }
}