package com.stephen.core.model;

public class Dictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dictionary.id
     *
     * @mbggenerated Wed Jan 11 10:00:27 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dictionary.name
     *
     * @mbggenerated Wed Jan 11 10:00:27 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dictionary.value
     *
     * @mbggenerated Wed Jan 11 10:00:27 CST 2017
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dictionary.type
     *
     * @mbggenerated Wed Jan 11 10:00:27 CST 2017
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dictionary.id
     *
     * @return the value of s_dictionary.id
     *
     * @mbggenerated Wed Jan 11 10:00:27 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dictionary.id
     *
     * @param id the value for s_dictionary.id
     *
     * @mbggenerated Wed Jan 11 10:00:27 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dictionary.name
     *
     * @return the value of s_dictionary.name
     *
     * @mbggenerated Wed Jan 11 10:00:27 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dictionary.name
     *
     * @param name the value for s_dictionary.name
     *
     * @mbggenerated Wed Jan 11 10:00:27 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dictionary.value
     *
     * @return the value of s_dictionary.value
     *
     * @mbggenerated Wed Jan 11 10:00:27 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dictionary.value
     *
     * @param value the value for s_dictionary.value
     *
     * @mbggenerated Wed Jan 11 10:00:27 CST 2017
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dictionary.type
     *
     * @return the value of s_dictionary.type
     *
     * @mbggenerated Wed Jan 11 10:00:27 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dictionary.type
     *
     * @param type the value for s_dictionary.type
     *
     * @mbggenerated Wed Jan 11 10:00:27 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }
}