package com.stephen.core.model;

public class File {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_file.file_path
     *
     * @mbggenerated Wed Jan 11 10:00:54 CST 2017
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_file.file_name
     *
     * @mbggenerated Wed Jan 11 10:00:54 CST 2017
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_file.file_isvalid
     *
     * @mbggenerated Wed Jan 11 10:00:54 CST 2017
     */
    private Boolean fileIsvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_file.content_id
     *
     * @mbggenerated Wed Jan 11 10:00:54 CST 2017
     */
    private Integer contentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_file.file_path
     *
     * @return the value of s_file.file_path
     *
     * @mbggenerated Wed Jan 11 10:00:54 CST 2017
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_file.file_path
     *
     * @param filePath the value for s_file.file_path
     *
     * @mbggenerated Wed Jan 11 10:00:54 CST 2017
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_file.file_name
     *
     * @return the value of s_file.file_name
     *
     * @mbggenerated Wed Jan 11 10:00:54 CST 2017
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_file.file_name
     *
     * @param fileName the value for s_file.file_name
     *
     * @mbggenerated Wed Jan 11 10:00:54 CST 2017
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_file.file_isvalid
     *
     * @return the value of s_file.file_isvalid
     *
     * @mbggenerated Wed Jan 11 10:00:54 CST 2017
     */
    public Boolean getFileIsvalid() {
        return fileIsvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_file.file_isvalid
     *
     * @param fileIsvalid the value for s_file.file_isvalid
     *
     * @mbggenerated Wed Jan 11 10:00:54 CST 2017
     */
    public void setFileIsvalid(Boolean fileIsvalid) {
        this.fileIsvalid = fileIsvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_file.content_id
     *
     * @return the value of s_file.content_id
     *
     * @mbggenerated Wed Jan 11 10:00:54 CST 2017
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_file.content_id
     *
     * @param contentId the value for s_file.content_id
     *
     * @mbggenerated Wed Jan 11 10:00:54 CST 2017
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }
}