package com.stephen.core.model;

public class Group {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_group.group_id
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_group.group_name
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_group.priority
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_group.need_captcha
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    private Boolean needCaptcha;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_group.need_check
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    private Boolean needCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_group.allow_per_day
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    private Integer allowPerDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_group.allow_max_file
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    private Integer allowMaxFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_group.allow_suffix
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    private String allowSuffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_group.is_reg_def
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    private Boolean isRegDef;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_group.group_id
     *
     * @return the value of s_group.group_id
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_group.group_id
     *
     * @param groupId the value for s_group.group_id
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_group.group_name
     *
     * @return the value of s_group.group_name
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_group.group_name
     *
     * @param groupName the value for s_group.group_name
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_group.priority
     *
     * @return the value of s_group.priority
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_group.priority
     *
     * @param priority the value for s_group.priority
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_group.need_captcha
     *
     * @return the value of s_group.need_captcha
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    public Boolean getNeedCaptcha() {
        return needCaptcha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_group.need_captcha
     *
     * @param needCaptcha the value for s_group.need_captcha
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    public void setNeedCaptcha(Boolean needCaptcha) {
        this.needCaptcha = needCaptcha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_group.need_check
     *
     * @return the value of s_group.need_check
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    public Boolean getNeedCheck() {
        return needCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_group.need_check
     *
     * @param needCheck the value for s_group.need_check
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    public void setNeedCheck(Boolean needCheck) {
        this.needCheck = needCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_group.allow_per_day
     *
     * @return the value of s_group.allow_per_day
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    public Integer getAllowPerDay() {
        return allowPerDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_group.allow_per_day
     *
     * @param allowPerDay the value for s_group.allow_per_day
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    public void setAllowPerDay(Integer allowPerDay) {
        this.allowPerDay = allowPerDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_group.allow_max_file
     *
     * @return the value of s_group.allow_max_file
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    public Integer getAllowMaxFile() {
        return allowMaxFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_group.allow_max_file
     *
     * @param allowMaxFile the value for s_group.allow_max_file
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    public void setAllowMaxFile(Integer allowMaxFile) {
        this.allowMaxFile = allowMaxFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_group.allow_suffix
     *
     * @return the value of s_group.allow_suffix
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    public String getAllowSuffix() {
        return allowSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_group.allow_suffix
     *
     * @param allowSuffix the value for s_group.allow_suffix
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    public void setAllowSuffix(String allowSuffix) {
        this.allowSuffix = allowSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_group.is_reg_def
     *
     * @return the value of s_group.is_reg_def
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    public Boolean getIsRegDef() {
        return isRegDef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_group.is_reg_def
     *
     * @param isRegDef the value for s_group.is_reg_def
     *
     * @mbggenerated Wed Jan 11 10:01:14 CST 2017
     */
    public void setIsRegDef(Boolean isRegDef) {
        this.isRegDef = isRegDef;
    }
}