package com.stephen.core.model;

import java.util.Date;

public class Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_log.log_id
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_log.user_id
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_log.site_id
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    private Integer siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_log.category
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_log.log_time
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    private Date logTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_log.ip
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_log.url
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_log.title
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_log.content
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_log.log_id
     *
     * @return the value of s_log.log_id
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_log.log_id
     *
     * @param logId the value for s_log.log_id
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_log.user_id
     *
     * @return the value of s_log.user_id
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_log.user_id
     *
     * @param userId the value for s_log.user_id
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_log.site_id
     *
     * @return the value of s_log.site_id
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_log.site_id
     *
     * @param siteId the value for s_log.site_id
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_log.category
     *
     * @return the value of s_log.category
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_log.category
     *
     * @param category the value for s_log.category
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_log.log_time
     *
     * @return the value of s_log.log_time
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    public Date getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_log.log_time
     *
     * @param logTime the value for s_log.log_time
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    public void setLogTime(Date logTime) {
        this.logTime = logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_log.ip
     *
     * @return the value of s_log.ip
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_log.ip
     *
     * @param ip the value for s_log.ip
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_log.url
     *
     * @return the value of s_log.url
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_log.url
     *
     * @param url the value for s_log.url
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_log.title
     *
     * @return the value of s_log.title
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_log.title
     *
     * @param title the value for s_log.title
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_log.content
     *
     * @return the value of s_log.content
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_log.content
     *
     * @param content the value for s_log.content
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }
}