package com.stephen.core.model;

public class Model {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model.model_id
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model.model_name
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    private String modelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model.model_path
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    private String modelPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model.tpl_channel_prefix
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    private String tplChannelPrefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model.tpl_content_prefix
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    private String tplContentPrefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model.title_img_width
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    private Integer titleImgWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model.title_img_height
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    private Integer titleImgHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model.content_img_width
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    private Integer contentImgWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model.content_img_height
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    private Integer contentImgHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model.priority
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model.has_content
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    private Boolean hasContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model.is_disabled
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    private Boolean isDisabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model.is_def
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    private Boolean isDef;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model.model_id
     *
     * @return the value of s_model.model_id
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model.model_id
     *
     * @param modelId the value for s_model.model_id
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model.model_name
     *
     * @return the value of s_model.model_name
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model.model_name
     *
     * @param modelName the value for s_model.model_name
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model.model_path
     *
     * @return the value of s_model.model_path
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public String getModelPath() {
        return modelPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model.model_path
     *
     * @param modelPath the value for s_model.model_path
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public void setModelPath(String modelPath) {
        this.modelPath = modelPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model.tpl_channel_prefix
     *
     * @return the value of s_model.tpl_channel_prefix
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public String getTplChannelPrefix() {
        return tplChannelPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model.tpl_channel_prefix
     *
     * @param tplChannelPrefix the value for s_model.tpl_channel_prefix
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public void setTplChannelPrefix(String tplChannelPrefix) {
        this.tplChannelPrefix = tplChannelPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model.tpl_content_prefix
     *
     * @return the value of s_model.tpl_content_prefix
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public String getTplContentPrefix() {
        return tplContentPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model.tpl_content_prefix
     *
     * @param tplContentPrefix the value for s_model.tpl_content_prefix
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public void setTplContentPrefix(String tplContentPrefix) {
        this.tplContentPrefix = tplContentPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model.title_img_width
     *
     * @return the value of s_model.title_img_width
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public Integer getTitleImgWidth() {
        return titleImgWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model.title_img_width
     *
     * @param titleImgWidth the value for s_model.title_img_width
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public void setTitleImgWidth(Integer titleImgWidth) {
        this.titleImgWidth = titleImgWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model.title_img_height
     *
     * @return the value of s_model.title_img_height
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public Integer getTitleImgHeight() {
        return titleImgHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model.title_img_height
     *
     * @param titleImgHeight the value for s_model.title_img_height
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public void setTitleImgHeight(Integer titleImgHeight) {
        this.titleImgHeight = titleImgHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model.content_img_width
     *
     * @return the value of s_model.content_img_width
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public Integer getContentImgWidth() {
        return contentImgWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model.content_img_width
     *
     * @param contentImgWidth the value for s_model.content_img_width
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public void setContentImgWidth(Integer contentImgWidth) {
        this.contentImgWidth = contentImgWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model.content_img_height
     *
     * @return the value of s_model.content_img_height
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public Integer getContentImgHeight() {
        return contentImgHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model.content_img_height
     *
     * @param contentImgHeight the value for s_model.content_img_height
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public void setContentImgHeight(Integer contentImgHeight) {
        this.contentImgHeight = contentImgHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model.priority
     *
     * @return the value of s_model.priority
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model.priority
     *
     * @param priority the value for s_model.priority
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model.has_content
     *
     * @return the value of s_model.has_content
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public Boolean getHasContent() {
        return hasContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model.has_content
     *
     * @param hasContent the value for s_model.has_content
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public void setHasContent(Boolean hasContent) {
        this.hasContent = hasContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model.is_disabled
     *
     * @return the value of s_model.is_disabled
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public Boolean getIsDisabled() {
        return isDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model.is_disabled
     *
     * @param isDisabled the value for s_model.is_disabled
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public void setIsDisabled(Boolean isDisabled) {
        this.isDisabled = isDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model.is_def
     *
     * @return the value of s_model.is_def
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public Boolean getIsDef() {
        return isDef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model.is_def
     *
     * @param isDef the value for s_model.is_def
     *
     * @mbggenerated Wed Jan 11 10:02:17 CST 2017
     */
    public void setIsDef(Boolean isDef) {
        this.isDef = isDef;
    }
}