package com.stephen.core.model;

public class Model_item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model_item.modelitem_id
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    private Integer modelitemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model_item.model_id
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model_item.field
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    private String field;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model_item.item_label
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    private String itemLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model_item.priority
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model_item.def_value
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    private String defValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model_item.opt_value
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    private String optValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model_item.text_size
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    private String textSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model_item.area_rows
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    private String areaRows;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model_item.area_cols
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    private String areaCols;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model_item.help
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    private String help;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model_item.help_position
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    private String helpPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model_item.data_type
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    private Integer dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model_item.is_single
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    private Boolean isSingle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model_item.is_channel
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    private Boolean isChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model_item.is_custom
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    private Boolean isCustom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_model_item.is_display
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    private Boolean isDisplay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model_item.modelitem_id
     *
     * @return the value of s_model_item.modelitem_id
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public Integer getModelitemId() {
        return modelitemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model_item.modelitem_id
     *
     * @param modelitemId the value for s_model_item.modelitem_id
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public void setModelitemId(Integer modelitemId) {
        this.modelitemId = modelitemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model_item.model_id
     *
     * @return the value of s_model_item.model_id
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model_item.model_id
     *
     * @param modelId the value for s_model_item.model_id
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model_item.field
     *
     * @return the value of s_model_item.field
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public String getField() {
        return field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model_item.field
     *
     * @param field the value for s_model_item.field
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public void setField(String field) {
        this.field = field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model_item.item_label
     *
     * @return the value of s_model_item.item_label
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public String getItemLabel() {
        return itemLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model_item.item_label
     *
     * @param itemLabel the value for s_model_item.item_label
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public void setItemLabel(String itemLabel) {
        this.itemLabel = itemLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model_item.priority
     *
     * @return the value of s_model_item.priority
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model_item.priority
     *
     * @param priority the value for s_model_item.priority
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model_item.def_value
     *
     * @return the value of s_model_item.def_value
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public String getDefValue() {
        return defValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model_item.def_value
     *
     * @param defValue the value for s_model_item.def_value
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public void setDefValue(String defValue) {
        this.defValue = defValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model_item.opt_value
     *
     * @return the value of s_model_item.opt_value
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public String getOptValue() {
        return optValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model_item.opt_value
     *
     * @param optValue the value for s_model_item.opt_value
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public void setOptValue(String optValue) {
        this.optValue = optValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model_item.text_size
     *
     * @return the value of s_model_item.text_size
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public String getTextSize() {
        return textSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model_item.text_size
     *
     * @param textSize the value for s_model_item.text_size
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public void setTextSize(String textSize) {
        this.textSize = textSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model_item.area_rows
     *
     * @return the value of s_model_item.area_rows
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public String getAreaRows() {
        return areaRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model_item.area_rows
     *
     * @param areaRows the value for s_model_item.area_rows
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public void setAreaRows(String areaRows) {
        this.areaRows = areaRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model_item.area_cols
     *
     * @return the value of s_model_item.area_cols
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public String getAreaCols() {
        return areaCols;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model_item.area_cols
     *
     * @param areaCols the value for s_model_item.area_cols
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public void setAreaCols(String areaCols) {
        this.areaCols = areaCols;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model_item.help
     *
     * @return the value of s_model_item.help
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public String getHelp() {
        return help;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model_item.help
     *
     * @param help the value for s_model_item.help
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public void setHelp(String help) {
        this.help = help;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model_item.help_position
     *
     * @return the value of s_model_item.help_position
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public String getHelpPosition() {
        return helpPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model_item.help_position
     *
     * @param helpPosition the value for s_model_item.help_position
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public void setHelpPosition(String helpPosition) {
        this.helpPosition = helpPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model_item.data_type
     *
     * @return the value of s_model_item.data_type
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model_item.data_type
     *
     * @param dataType the value for s_model_item.data_type
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model_item.is_single
     *
     * @return the value of s_model_item.is_single
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public Boolean getIsSingle() {
        return isSingle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model_item.is_single
     *
     * @param isSingle the value for s_model_item.is_single
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public void setIsSingle(Boolean isSingle) {
        this.isSingle = isSingle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model_item.is_channel
     *
     * @return the value of s_model_item.is_channel
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public Boolean getIsChannel() {
        return isChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model_item.is_channel
     *
     * @param isChannel the value for s_model_item.is_channel
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public void setIsChannel(Boolean isChannel) {
        this.isChannel = isChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model_item.is_custom
     *
     * @return the value of s_model_item.is_custom
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public Boolean getIsCustom() {
        return isCustom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model_item.is_custom
     *
     * @param isCustom the value for s_model_item.is_custom
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public void setIsCustom(Boolean isCustom) {
        this.isCustom = isCustom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_model_item.is_display
     *
     * @return the value of s_model_item.is_display
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public Boolean getIsDisplay() {
        return isDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_model_item.is_display
     *
     * @param isDisplay the value for s_model_item.is_display
     *
     * @mbggenerated Wed Jan 11 10:02:31 CST 2017
     */
    public void setIsDisplay(Boolean isDisplay) {
        this.isDisplay = isDisplay;
    }
}