package com.stephen.core.model;

public class Navi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_navi.navi_id
     *
     * @mbggenerated Thu Feb 16 00:56:34 CST 2017
     */
    private Integer naviId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_navi.navi_name
     *
     * @mbggenerated Thu Feb 16 00:56:34 CST 2017
     */
    private String naviName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_navi.has_child
     *
     * @mbggenerated Thu Feb 16 00:56:34 CST 2017
     */
    private Integer hasChild;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_navi.navi_id
     *
     * @return the value of s_navi.navi_id
     *
     * @mbggenerated Thu Feb 16 00:56:34 CST 2017
     */
    public Integer getNaviId() {
        return naviId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_navi.navi_id
     *
     * @param naviId the value for s_navi.navi_id
     *
     * @mbggenerated Thu Feb 16 00:56:34 CST 2017
     */
    public void setNaviId(Integer naviId) {
        this.naviId = naviId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_navi.navi_name
     *
     * @return the value of s_navi.navi_name
     *
     * @mbggenerated Thu Feb 16 00:56:34 CST 2017
     */
    public String getNaviName() {
        return naviName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_navi.navi_name
     *
     * @param naviName the value for s_navi.navi_name
     *
     * @mbggenerated Thu Feb 16 00:56:34 CST 2017
     */
    public void setNaviName(String naviName) {
        this.naviName = naviName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_navi.has_child
     *
     * @return the value of s_navi.has_child
     *
     * @mbggenerated Thu Feb 16 00:56:34 CST 2017
     */
    public Integer getHasChild() {
        return hasChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_navi.has_child
     *
     * @param hasChild the value for s_navi.has_child
     *
     * @mbggenerated Thu Feb 16 00:56:34 CST 2017
     */
    public void setHasChild(Integer hasChild) {
        this.hasChild = hasChild;
    }
}