package com.stephen.core.model;

import java.util.Date;

public class ReceiverMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_receiver_message.msg_re_id
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    private Integer msgReId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_receiver_message.msg_title
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    private String msgTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_receiver_message.send_time
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_receiver_message.msg_send_user
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    private Integer msgSendUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_receiver_message.msg_receiver_user
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    private Integer msgReceiverUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_receiver_message.site_id
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    private Integer siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_receiver_message.msg_status
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    private Boolean msgStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_receiver_message.msg_box
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    private Integer msgBox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_receiver_message.msg_id
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    private Integer msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_receiver_message.msg_content
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    private String msgContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_receiver_message.msg_re_id
     *
     * @return the value of s_receiver_message.msg_re_id
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public Integer getMsgReId() {
        return msgReId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_receiver_message.msg_re_id
     *
     * @param msgReId the value for s_receiver_message.msg_re_id
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public void setMsgReId(Integer msgReId) {
        this.msgReId = msgReId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_receiver_message.msg_title
     *
     * @return the value of s_receiver_message.msg_title
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public String getMsgTitle() {
        return msgTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_receiver_message.msg_title
     *
     * @param msgTitle the value for s_receiver_message.msg_title
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public void setMsgTitle(String msgTitle) {
        this.msgTitle = msgTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_receiver_message.send_time
     *
     * @return the value of s_receiver_message.send_time
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_receiver_message.send_time
     *
     * @param sendTime the value for s_receiver_message.send_time
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_receiver_message.msg_send_user
     *
     * @return the value of s_receiver_message.msg_send_user
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public Integer getMsgSendUser() {
        return msgSendUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_receiver_message.msg_send_user
     *
     * @param msgSendUser the value for s_receiver_message.msg_send_user
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public void setMsgSendUser(Integer msgSendUser) {
        this.msgSendUser = msgSendUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_receiver_message.msg_receiver_user
     *
     * @return the value of s_receiver_message.msg_receiver_user
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public Integer getMsgReceiverUser() {
        return msgReceiverUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_receiver_message.msg_receiver_user
     *
     * @param msgReceiverUser the value for s_receiver_message.msg_receiver_user
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public void setMsgReceiverUser(Integer msgReceiverUser) {
        this.msgReceiverUser = msgReceiverUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_receiver_message.site_id
     *
     * @return the value of s_receiver_message.site_id
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_receiver_message.site_id
     *
     * @param siteId the value for s_receiver_message.site_id
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_receiver_message.msg_status
     *
     * @return the value of s_receiver_message.msg_status
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public Boolean getMsgStatus() {
        return msgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_receiver_message.msg_status
     *
     * @param msgStatus the value for s_receiver_message.msg_status
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public void setMsgStatus(Boolean msgStatus) {
        this.msgStatus = msgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_receiver_message.msg_box
     *
     * @return the value of s_receiver_message.msg_box
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public Integer getMsgBox() {
        return msgBox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_receiver_message.msg_box
     *
     * @param msgBox the value for s_receiver_message.msg_box
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public void setMsgBox(Integer msgBox) {
        this.msgBox = msgBox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_receiver_message.msg_id
     *
     * @return the value of s_receiver_message.msg_id
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public Integer getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_receiver_message.msg_id
     *
     * @param msgId the value for s_receiver_message.msg_id
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public void setMsgId(Integer msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_receiver_message.msg_content
     *
     * @return the value of s_receiver_message.msg_content
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_receiver_message.msg_content
     *
     * @param msgContent the value for s_receiver_message.msg_content
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent;
    }
}