package com.stephen.core.model;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.role_id
     *
     * @mbggenerated Wed Jan 11 10:05:26 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.site_id
     *
     * @mbggenerated Wed Jan 11 10:05:26 CST 2017
     */
    private Integer siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.role_name
     *
     * @mbggenerated Wed Jan 11 10:05:26 CST 2017
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.priority
     *
     * @mbggenerated Wed Jan 11 10:05:26 CST 2017
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.is_super
     *
     * @mbggenerated Wed Jan 11 10:05:26 CST 2017
     */
    private String isSuper;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.role_id
     *
     * @return the value of s_role.role_id
     *
     * @mbggenerated Wed Jan 11 10:05:26 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.role_id
     *
     * @param roleId the value for s_role.role_id
     *
     * @mbggenerated Wed Jan 11 10:05:26 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.site_id
     *
     * @return the value of s_role.site_id
     *
     * @mbggenerated Wed Jan 11 10:05:26 CST 2017
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.site_id
     *
     * @param siteId the value for s_role.site_id
     *
     * @mbggenerated Wed Jan 11 10:05:26 CST 2017
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.role_name
     *
     * @return the value of s_role.role_name
     *
     * @mbggenerated Wed Jan 11 10:05:26 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.role_name
     *
     * @param roleName the value for s_role.role_name
     *
     * @mbggenerated Wed Jan 11 10:05:26 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.priority
     *
     * @return the value of s_role.priority
     *
     * @mbggenerated Wed Jan 11 10:05:26 CST 2017
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.priority
     *
     * @param priority the value for s_role.priority
     *
     * @mbggenerated Wed Jan 11 10:05:26 CST 2017
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.is_super
     *
     * @return the value of s_role.is_super
     *
     * @mbggenerated Wed Jan 11 10:05:26 CST 2017
     */
    public String getIsSuper() {
        return isSuper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.is_super
     *
     * @param isSuper the value for s_role.is_super
     *
     * @mbggenerated Wed Jan 11 10:05:26 CST 2017
     */
    public void setIsSuper(String isSuper) {
        this.isSuper = isSuper;
    }
}