package com.stephen.core.model;

public class RolePermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role_permission.role_id
     *
     * @mbggenerated Wed Jan 11 10:05:54 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role_permission.uri
     *
     * @mbggenerated Wed Jan 11 10:05:54 CST 2017
     */
    private String uri;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role_permission.role_id
     *
     * @return the value of s_role_permission.role_id
     *
     * @mbggenerated Wed Jan 11 10:05:54 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role_permission.role_id
     *
     * @param roleId the value for s_role_permission.role_id
     *
     * @mbggenerated Wed Jan 11 10:05:54 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role_permission.uri
     *
     * @return the value of s_role_permission.uri
     *
     * @mbggenerated Wed Jan 11 10:05:54 CST 2017
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role_permission.uri
     *
     * @param uri the value for s_role_permission.uri
     *
     * @mbggenerated Wed Jan 11 10:05:54 CST 2017
     */
    public void setUri(String uri) {
        this.uri = uri;
    }
}