package com.stephen.core.model;

import java.util.Date;

public class SiteAccessCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_count.access_count
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    private Integer accessCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_count.page_count
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    private Integer pageCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_count.visitors
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    private Integer visitors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_count.statistic_date
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    private Date statisticDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_count.site_id
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    private Integer siteId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_count.access_count
     *
     * @return the value of s_site_access_count.access_count
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    public Integer getAccessCount() {
        return accessCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_count.access_count
     *
     * @param accessCount the value for s_site_access_count.access_count
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    public void setAccessCount(Integer accessCount) {
        this.accessCount = accessCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_count.page_count
     *
     * @return the value of s_site_access_count.page_count
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    public Integer getPageCount() {
        return pageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_count.page_count
     *
     * @param pageCount the value for s_site_access_count.page_count
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    public void setPageCount(Integer pageCount) {
        this.pageCount = pageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_count.visitors
     *
     * @return the value of s_site_access_count.visitors
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    public Integer getVisitors() {
        return visitors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_count.visitors
     *
     * @param visitors the value for s_site_access_count.visitors
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    public void setVisitors(Integer visitors) {
        this.visitors = visitors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_count.statistic_date
     *
     * @return the value of s_site_access_count.statistic_date
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    public Date getStatisticDate() {
        return statisticDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_count.statistic_date
     *
     * @param statisticDate the value for s_site_access_count.statistic_date
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    public void setStatisticDate(Date statisticDate) {
        this.statisticDate = statisticDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_count.site_id
     *
     * @return the value of s_site_access_count.site_id
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_count.site_id
     *
     * @param siteId the value for s_site_access_count.site_id
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }
}