package com.stephen.core.model;

import java.util.Date;

public class SiteAccessPages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_pages.access_pages_id
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    private Integer accessPagesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_pages.access_page
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    private String accessPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_pages.session_id
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_pages.access_date
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    private Date accessDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_pages.access_time
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    private Date accessTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_pages.visit_second
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    private Integer visitSecond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_pages.page_index
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    private Integer pageIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_pages.site_id
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    private Integer siteId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_pages.access_pages_id
     *
     * @return the value of s_site_access_pages.access_pages_id
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    public Integer getAccessPagesId() {
        return accessPagesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_pages.access_pages_id
     *
     * @param accessPagesId the value for s_site_access_pages.access_pages_id
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    public void setAccessPagesId(Integer accessPagesId) {
        this.accessPagesId = accessPagesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_pages.access_page
     *
     * @return the value of s_site_access_pages.access_page
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    public String getAccessPage() {
        return accessPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_pages.access_page
     *
     * @param accessPage the value for s_site_access_pages.access_page
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    public void setAccessPage(String accessPage) {
        this.accessPage = accessPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_pages.session_id
     *
     * @return the value of s_site_access_pages.session_id
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_pages.session_id
     *
     * @param sessionId the value for s_site_access_pages.session_id
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_pages.access_date
     *
     * @return the value of s_site_access_pages.access_date
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    public Date getAccessDate() {
        return accessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_pages.access_date
     *
     * @param accessDate the value for s_site_access_pages.access_date
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    public void setAccessDate(Date accessDate) {
        this.accessDate = accessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_pages.access_time
     *
     * @return the value of s_site_access_pages.access_time
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    public Date getAccessTime() {
        return accessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_pages.access_time
     *
     * @param accessTime the value for s_site_access_pages.access_time
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    public void setAccessTime(Date accessTime) {
        this.accessTime = accessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_pages.visit_second
     *
     * @return the value of s_site_access_pages.visit_second
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    public Integer getVisitSecond() {
        return visitSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_pages.visit_second
     *
     * @param visitSecond the value for s_site_access_pages.visit_second
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    public void setVisitSecond(Integer visitSecond) {
        this.visitSecond = visitSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_pages.page_index
     *
     * @return the value of s_site_access_pages.page_index
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    public Integer getPageIndex() {
        return pageIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_pages.page_index
     *
     * @param pageIndex the value for s_site_access_pages.page_index
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    public void setPageIndex(Integer pageIndex) {
        this.pageIndex = pageIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_pages.site_id
     *
     * @return the value of s_site_access_pages.site_id
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_pages.site_id
     *
     * @param siteId the value for s_site_access_pages.site_id
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }
}