package com.stephen.core.model;

import java.util.Date;

public class SiteAccess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access.access_id
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    private Integer accessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access.session_id
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access.site_id
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    private Integer siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access.access_time
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    private Date accessTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access.access_date
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    private Date accessDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access.ip
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access.area
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access.access_source
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    private String accessSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access.external_link
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    private String externalLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access.engine
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    private String engine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access.entry_page
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    private String entryPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access.last_stop_page
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    private String lastStopPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access.visit_second
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    private Integer visitSecond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access.visit_page_count
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    private Integer visitPageCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access.operating_system
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    private String operatingSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access.browser
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    private String browser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access.keyword
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    private String keyword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access.access_id
     *
     * @return the value of s_site_access.access_id
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public Integer getAccessId() {
        return accessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access.access_id
     *
     * @param accessId the value for s_site_access.access_id
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public void setAccessId(Integer accessId) {
        this.accessId = accessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access.session_id
     *
     * @return the value of s_site_access.session_id
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access.session_id
     *
     * @param sessionId the value for s_site_access.session_id
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access.site_id
     *
     * @return the value of s_site_access.site_id
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access.site_id
     *
     * @param siteId the value for s_site_access.site_id
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access.access_time
     *
     * @return the value of s_site_access.access_time
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public Date getAccessTime() {
        return accessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access.access_time
     *
     * @param accessTime the value for s_site_access.access_time
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public void setAccessTime(Date accessTime) {
        this.accessTime = accessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access.access_date
     *
     * @return the value of s_site_access.access_date
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public Date getAccessDate() {
        return accessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access.access_date
     *
     * @param accessDate the value for s_site_access.access_date
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public void setAccessDate(Date accessDate) {
        this.accessDate = accessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access.ip
     *
     * @return the value of s_site_access.ip
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access.ip
     *
     * @param ip the value for s_site_access.ip
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access.area
     *
     * @return the value of s_site_access.area
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access.area
     *
     * @param area the value for s_site_access.area
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access.access_source
     *
     * @return the value of s_site_access.access_source
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public String getAccessSource() {
        return accessSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access.access_source
     *
     * @param accessSource the value for s_site_access.access_source
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public void setAccessSource(String accessSource) {
        this.accessSource = accessSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access.external_link
     *
     * @return the value of s_site_access.external_link
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public String getExternalLink() {
        return externalLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access.external_link
     *
     * @param externalLink the value for s_site_access.external_link
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public void setExternalLink(String externalLink) {
        this.externalLink = externalLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access.engine
     *
     * @return the value of s_site_access.engine
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public String getEngine() {
        return engine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access.engine
     *
     * @param engine the value for s_site_access.engine
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public void setEngine(String engine) {
        this.engine = engine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access.entry_page
     *
     * @return the value of s_site_access.entry_page
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public String getEntryPage() {
        return entryPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access.entry_page
     *
     * @param entryPage the value for s_site_access.entry_page
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public void setEntryPage(String entryPage) {
        this.entryPage = entryPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access.last_stop_page
     *
     * @return the value of s_site_access.last_stop_page
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public String getLastStopPage() {
        return lastStopPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access.last_stop_page
     *
     * @param lastStopPage the value for s_site_access.last_stop_page
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public void setLastStopPage(String lastStopPage) {
        this.lastStopPage = lastStopPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access.visit_second
     *
     * @return the value of s_site_access.visit_second
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public Integer getVisitSecond() {
        return visitSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access.visit_second
     *
     * @param visitSecond the value for s_site_access.visit_second
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public void setVisitSecond(Integer visitSecond) {
        this.visitSecond = visitSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access.visit_page_count
     *
     * @return the value of s_site_access.visit_page_count
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public Integer getVisitPageCount() {
        return visitPageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access.visit_page_count
     *
     * @param visitPageCount the value for s_site_access.visit_page_count
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public void setVisitPageCount(Integer visitPageCount) {
        this.visitPageCount = visitPageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access.operating_system
     *
     * @return the value of s_site_access.operating_system
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public String getOperatingSystem() {
        return operatingSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access.operating_system
     *
     * @param operatingSystem the value for s_site_access.operating_system
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public void setOperatingSystem(String operatingSystem) {
        this.operatingSystem = operatingSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access.browser
     *
     * @return the value of s_site_access.browser
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access.browser
     *
     * @param browser the value for s_site_access.browser
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public void setBrowser(String browser) {
        this.browser = browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access.keyword
     *
     * @return the value of s_site_access.keyword
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access.keyword
     *
     * @param keyword the value for s_site_access.keyword
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }
}