package com.stephen.core.model;

import java.util.Date;

public class SiteAccessStatistic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_statistic.access_statistic_id
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    private Integer accessStatisticId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_statistic.statistic_date
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    private Date statisticDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_statistic.pv
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    private Integer pv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_statistic.ip
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    private Integer ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_statistic.visitors
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    private Integer visitors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_statistic.pages_aver
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    private Integer pagesAver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_statistic.visit_second_aver
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    private Integer visitSecondAver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_statistic.site_id
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    private Integer siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_statistic.statisitc_type
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    private String statisitcType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_site_access_statistic.statistic_column_value
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    private String statisticColumnValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_statistic.access_statistic_id
     *
     * @return the value of s_site_access_statistic.access_statistic_id
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public Integer getAccessStatisticId() {
        return accessStatisticId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_statistic.access_statistic_id
     *
     * @param accessStatisticId the value for s_site_access_statistic.access_statistic_id
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public void setAccessStatisticId(Integer accessStatisticId) {
        this.accessStatisticId = accessStatisticId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_statistic.statistic_date
     *
     * @return the value of s_site_access_statistic.statistic_date
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public Date getStatisticDate() {
        return statisticDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_statistic.statistic_date
     *
     * @param statisticDate the value for s_site_access_statistic.statistic_date
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public void setStatisticDate(Date statisticDate) {
        this.statisticDate = statisticDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_statistic.pv
     *
     * @return the value of s_site_access_statistic.pv
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public Integer getPv() {
        return pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_statistic.pv
     *
     * @param pv the value for s_site_access_statistic.pv
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public void setPv(Integer pv) {
        this.pv = pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_statistic.ip
     *
     * @return the value of s_site_access_statistic.ip
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public Integer getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_statistic.ip
     *
     * @param ip the value for s_site_access_statistic.ip
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public void setIp(Integer ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_statistic.visitors
     *
     * @return the value of s_site_access_statistic.visitors
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public Integer getVisitors() {
        return visitors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_statistic.visitors
     *
     * @param visitors the value for s_site_access_statistic.visitors
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public void setVisitors(Integer visitors) {
        this.visitors = visitors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_statistic.pages_aver
     *
     * @return the value of s_site_access_statistic.pages_aver
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public Integer getPagesAver() {
        return pagesAver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_statistic.pages_aver
     *
     * @param pagesAver the value for s_site_access_statistic.pages_aver
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public void setPagesAver(Integer pagesAver) {
        this.pagesAver = pagesAver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_statistic.visit_second_aver
     *
     * @return the value of s_site_access_statistic.visit_second_aver
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public Integer getVisitSecondAver() {
        return visitSecondAver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_statistic.visit_second_aver
     *
     * @param visitSecondAver the value for s_site_access_statistic.visit_second_aver
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public void setVisitSecondAver(Integer visitSecondAver) {
        this.visitSecondAver = visitSecondAver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_statistic.site_id
     *
     * @return the value of s_site_access_statistic.site_id
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_statistic.site_id
     *
     * @param siteId the value for s_site_access_statistic.site_id
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_statistic.statisitc_type
     *
     * @return the value of s_site_access_statistic.statisitc_type
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public String getStatisitcType() {
        return statisitcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_statistic.statisitc_type
     *
     * @param statisitcType the value for s_site_access_statistic.statisitc_type
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public void setStatisitcType(String statisitcType) {
        this.statisitcType = statisitcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_site_access_statistic.statistic_column_value
     *
     * @return the value of s_site_access_statistic.statistic_column_value
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public String getStatisticColumnValue() {
        return statisticColumnValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_site_access_statistic.statistic_column_value
     *
     * @param statisticColumnValue the value for s_site_access_statistic.statistic_column_value
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    public void setStatisticColumnValue(String statisticColumnValue) {
        this.statisticColumnValue = statisticColumnValue;
    }
}