package com.stephen.core.model;

public class Topic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_topic.topic_id
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    private Integer topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_topic.channel_id
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    private Integer channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_topic.topic_name
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    private String topicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_topic.short_name
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_topic.keywords
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_topic.description
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_topic.title_img
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    private String titleImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_topic.content_img
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    private String contentImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_topic.tpl_content
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    private String tplContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_topic.priority
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_topic.is_recommend
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    private Boolean isRecommend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_topic.topic_id
     *
     * @return the value of s_topic.topic_id
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_topic.topic_id
     *
     * @param topicId the value for s_topic.topic_id
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_topic.channel_id
     *
     * @return the value of s_topic.channel_id
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_topic.channel_id
     *
     * @param channelId the value for s_topic.channel_id
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_topic.topic_name
     *
     * @return the value of s_topic.topic_name
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public String getTopicName() {
        return topicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_topic.topic_name
     *
     * @param topicName the value for s_topic.topic_name
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public void setTopicName(String topicName) {
        this.topicName = topicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_topic.short_name
     *
     * @return the value of s_topic.short_name
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_topic.short_name
     *
     * @param shortName the value for s_topic.short_name
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_topic.keywords
     *
     * @return the value of s_topic.keywords
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_topic.keywords
     *
     * @param keywords the value for s_topic.keywords
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_topic.description
     *
     * @return the value of s_topic.description
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_topic.description
     *
     * @param description the value for s_topic.description
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_topic.title_img
     *
     * @return the value of s_topic.title_img
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public String getTitleImg() {
        return titleImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_topic.title_img
     *
     * @param titleImg the value for s_topic.title_img
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public void setTitleImg(String titleImg) {
        this.titleImg = titleImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_topic.content_img
     *
     * @return the value of s_topic.content_img
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public String getContentImg() {
        return contentImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_topic.content_img
     *
     * @param contentImg the value for s_topic.content_img
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public void setContentImg(String contentImg) {
        this.contentImg = contentImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_topic.tpl_content
     *
     * @return the value of s_topic.tpl_content
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public String getTplContent() {
        return tplContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_topic.tpl_content
     *
     * @param tplContent the value for s_topic.tpl_content
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public void setTplContent(String tplContent) {
        this.tplContent = tplContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_topic.priority
     *
     * @return the value of s_topic.priority
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_topic.priority
     *
     * @param priority the value for s_topic.priority
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_topic.is_recommend
     *
     * @return the value of s_topic.is_recommend
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public Boolean getIsRecommend() {
        return isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_topic.is_recommend
     *
     * @param isRecommend the value for s_topic.is_recommend
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    public void setIsRecommend(Boolean isRecommend) {
        this.isRecommend = isRecommend;
    }
}