package com.stephen.core.model;

import java.util.Date;

public class UserExt {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user_ext.user_id
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user_ext.realname
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	private String realname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user_ext.gender
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	private Boolean gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user_ext.birthday
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user_ext.intro
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	private String intro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user_ext.comefrom
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	private String comefrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user_ext.qq
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	private String qq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user_ext.msn
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	private String msn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user_ext.phone
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user_ext.mobile
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user_ext.user_img
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	private String userImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user_ext.user_signature
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	private String userSignature;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user_ext.user_id
	 * @return  the value of s_user_ext.user_id
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user_ext.user_id
	 * @param userId  the value for s_user_ext.user_id
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user_ext.realname
	 * @return  the value of s_user_ext.realname
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user_ext.realname
	 * @param realname  the value for s_user_ext.realname
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user_ext.gender
	 * @return  the value of s_user_ext.gender
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public Boolean getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user_ext.gender
	 * @param gender  the value for s_user_ext.gender
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public void setGender(Boolean gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user_ext.birthday
	 * @return  the value of s_user_ext.birthday
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user_ext.birthday
	 * @param birthday  the value for s_user_ext.birthday
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user_ext.intro
	 * @return  the value of s_user_ext.intro
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public String getIntro() {
		return intro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user_ext.intro
	 * @param intro  the value for s_user_ext.intro
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public void setIntro(String intro) {
		this.intro = intro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user_ext.comefrom
	 * @return  the value of s_user_ext.comefrom
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public String getComefrom() {
		return comefrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user_ext.comefrom
	 * @param comefrom  the value for s_user_ext.comefrom
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public void setComefrom(String comefrom) {
		this.comefrom = comefrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user_ext.qq
	 * @return  the value of s_user_ext.qq
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user_ext.qq
	 * @param qq  the value for s_user_ext.qq
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public void setQq(String qq) {
		this.qq = qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user_ext.msn
	 * @return  the value of s_user_ext.msn
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public String getMsn() {
		return msn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user_ext.msn
	 * @param msn  the value for s_user_ext.msn
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public void setMsn(String msn) {
		this.msn = msn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user_ext.phone
	 * @return  the value of s_user_ext.phone
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user_ext.phone
	 * @param phone  the value for s_user_ext.phone
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user_ext.mobile
	 * @return  the value of s_user_ext.mobile
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user_ext.mobile
	 * @param mobile  the value for s_user_ext.mobile
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user_ext.user_img
	 * @return  the value of s_user_ext.user_img
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public String getUserImg() {
		return userImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user_ext.user_img
	 * @param userImg  the value for s_user_ext.user_img
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public void setUserImg(String userImg) {
		this.userImg = userImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user_ext.user_signature
	 * @return  the value of s_user_ext.user_signature
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public String getUserSignature() {
		return userSignature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user_ext.user_signature
	 * @param userSignature  the value for s_user_ext.user_signature
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	public void setUserSignature(String userSignature) {
		this.userSignature = userSignature;
	}
}