package com.stephen.core.model;

public class UserCollectionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_collection.content_id
     *
     * @mbggenerated Wed Jan 11 10:09:34 CST 2017
     */
    private Integer contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_collection.user_id
     *
     * @mbggenerated Wed Jan 11 10:09:34 CST 2017
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_collection.content_id
     *
     * @return the value of s_user_collection.content_id
     *
     * @mbggenerated Wed Jan 11 10:09:34 CST 2017
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_collection.content_id
     *
     * @param contentId the value for s_user_collection.content_id
     *
     * @mbggenerated Wed Jan 11 10:09:34 CST 2017
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_collection.user_id
     *
     * @return the value of s_user_collection.user_id
     *
     * @mbggenerated Wed Jan 11 10:09:34 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_collection.user_id
     *
     * @param userId the value for s_user_collection.user_id
     *
     * @mbggenerated Wed Jan 11 10:09:34 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}