package com.stephen.core.model;

public class UserMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_menu.menu_id
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_menu.menu_name
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_menu.menu_url
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    private String menuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_menu.priority
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_menu.user_id
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_menu.menu_id
     *
     * @return the value of s_user_menu.menu_id
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_menu.menu_id
     *
     * @param menuId the value for s_user_menu.menu_id
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_menu.menu_name
     *
     * @return the value of s_user_menu.menu_name
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_menu.menu_name
     *
     * @param menuName the value for s_user_menu.menu_name
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_menu.menu_url
     *
     * @return the value of s_user_menu.menu_url
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_menu.menu_url
     *
     * @param menuUrl the value for s_user_menu.menu_url
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_menu.priority
     *
     * @return the value of s_user_menu.priority
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_menu.priority
     *
     * @param priority the value for s_user_menu.priority
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_menu.user_id
     *
     * @return the value of s_user_menu.user_id
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_menu.user_id
     *
     * @param userId the value for s_user_menu.user_id
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}