package com.stephen.core.model;

public class UserAttr {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user_attr.user_id
	 * @mbggenerated  Thu Feb 16 11:01:46 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user_attr.attr_name
	 * @mbggenerated  Thu Feb 16 11:01:46 CST 2017
	 */
	private String attrName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user_attr.attr_value
	 * @mbggenerated  Thu Feb 16 11:01:46 CST 2017
	 */
	private String attrValue;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user_attr.user_id
	 * @return  the value of s_user_attr.user_id
	 * @mbggenerated  Thu Feb 16 11:01:46 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user_attr.user_id
	 * @param userId  the value for s_user_attr.user_id
	 * @mbggenerated  Thu Feb 16 11:01:46 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user_attr.attr_name
	 * @return  the value of s_user_attr.attr_name
	 * @mbggenerated  Thu Feb 16 11:01:46 CST 2017
	 */
	public String getAttrName() {
		return attrName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user_attr.attr_name
	 * @param attrName  the value for s_user_attr.attr_name
	 * @mbggenerated  Thu Feb 16 11:01:46 CST 2017
	 */
	public void setAttrName(String attrName) {
		this.attrName = attrName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user_attr.attr_value
	 * @return  the value of s_user_attr.attr_value
	 * @mbggenerated  Thu Feb 16 11:01:46 CST 2017
	 */
	public String getAttrValue() {
		return attrValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user_attr.attr_value
	 * @param attrValue  the value for s_user_attr.attr_value
	 * @mbggenerated  Thu Feb 16 11:01:46 CST 2017
	 */
	public void setAttrValue(String attrValue) {
		this.attrValue = attrValue;
	}
}