package com.stephen.core.model;

public class UserRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_role.role_id
     *
     * @mbggenerated Wed Jan 11 10:10:34 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_role.user_id
     *
     * @mbggenerated Wed Jan 11 10:10:34 CST 2017
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_role.role_id
     *
     * @return the value of s_user_role.role_id
     *
     * @mbggenerated Wed Jan 11 10:10:34 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_role.role_id
     *
     * @param roleId the value for s_user_role.role_id
     *
     * @mbggenerated Wed Jan 11 10:10:34 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_role.user_id
     *
     * @return the value of s_user_role.user_id
     *
     * @mbggenerated Wed Jan 11 10:10:34 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_role.user_id
     *
     * @param userId the value for s_user_role.user_id
     *
     * @mbggenerated Wed Jan 11 10:10:34 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}