package com.stephen.core.mapper;

import com.stephen.core.model.Authentication;

public interface AuthenticationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_authentication
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    int deleteByPrimaryKey(String authenticationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_authentication
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    int insert(Authentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_authentication
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    int insertSelective(Authentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_authentication
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    Authentication selectByPrimaryKey(String authenticationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_authentication
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    int updateByPrimaryKeySelective(Authentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_authentication
     *
     * @mbggenerated Tue Jan 10 19:57:59 CST 2017
     */
    int updateByPrimaryKey(Authentication record);
}