package com.stephen.core.mapper;

import com.stephen.core.model.ChannelCount;

public interface ChannelCountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_channel_count
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	int deleteByPrimaryKey(Integer channelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_channel_count
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	int insert(ChannelCount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_channel_count
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	int insertSelective(ChannelCount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_channel_count
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	ChannelCount selectByPrimaryKey(Integer channelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_channel_count
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	int updateByPrimaryKeySelective(ChannelCount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_channel_count
	 * @mbggenerated  Wed Feb 15 22:49:52 CST 2017
	 */
	int updateByPrimaryKey(ChannelCount record);
}