package com.stephen.core.mapper;

import com.stephen.core.model.ChannelAttr;

public interface ChannelAttrMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_channel_attr
	 * @mbggenerated  Wed Feb 15 22:49:38 CST 2017
	 */
	int insert(ChannelAttr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_channel_attr
	 * @mbggenerated  Wed Feb 15 22:49:38 CST 2017
	 */
	int insertSelective(ChannelAttr record);

	void deleteByChannelId(Integer id);
}