package com.stephen.core.mapper;

import com.stephen.core.model.ChannelTxt;

public interface ChannelTxtMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_channel_txt
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	int deleteByPrimaryKey(Integer channelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_channel_txt
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	int insert(ChannelTxt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_channel_txt
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	int insertSelective(ChannelTxt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_channel_txt
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	ChannelTxt selectByPrimaryKey(Integer channelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_channel_txt
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	int updateByPrimaryKeySelective(ChannelTxt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_channel_txt
	 * @mbggenerated  Wed Feb 15 22:50:52 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(ChannelTxt record);
}