package com.stephen.core.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.stephen.core.model.Channel;

public interface ChannelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_channel
	 * 
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	int deleteByPrimaryKey(Integer channelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_channel
	 * 
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	int insert(Channel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_channel
	 * 
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	int insertSelective(Channel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_channel
	 * 
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	Channel selectByPrimaryKey(Integer channelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_channel
	 * 
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	int updateByPrimaryKeySelective(Channel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_channel
	 * 
	 * @mbggenerated Wed Feb 15 22:49:23 CST 2017
	 */
	int updateByPrimaryKey(Channel record);

	List<Channel> selectPart(int count);

	List<Channel> selectAll();

	List<Channel> selectByParentId(Integer channelId);

	int selectLastId();

	Channel selectByPrimaryKeyWithoutAttr(Integer channelId);

	Channel findByPathForTag(@Param("path") String path);

	List<Channel> selectChild(Integer channelId);

}