package com.stephen.core.mapper;

import com.stephen.core.model.ChannelUserKey;

public interface ChannelUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_channel_user
     *
     * @mbggenerated Tue Jan 10 20:00:28 CST 2017
     */
    int deleteByPrimaryKey(ChannelUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_channel_user
     *
     * @mbggenerated Tue Jan 10 20:00:28 CST 2017
     */
    int insert(ChannelUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_channel_user
     *
     * @mbggenerated Tue Jan 10 20:00:28 CST 2017
     */
    int insertSelective(ChannelUserKey record);
}