package com.stephen.core.mapper;

import com.stephen.core.model.ChnlGroupContriKey;

public interface ChnlGroupContriMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_chnl_group_contri
     *
     * @mbggenerated Tue Jan 10 20:01:59 CST 2017
     */
    int deleteByPrimaryKey(ChnlGroupContriKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_chnl_group_contri
     *
     * @mbggenerated Tue Jan 10 20:01:59 CST 2017
     */
    int insert(ChnlGroupContriKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_chnl_group_contri
     *
     * @mbggenerated Tue Jan 10 20:01:59 CST 2017
     */
    int insertSelective(ChnlGroupContriKey record);
}