package com.stephen.core.mapper;

import com.stephen.core.model.ChnlGroupViewKey;

public interface ChnlGroupViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_chnl_group_view
     *
     * @mbggenerated Tue Jan 10 20:02:20 CST 2017
     */
    int deleteByPrimaryKey(ChnlGroupViewKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_chnl_group_view
     *
     * @mbggenerated Tue Jan 10 20:02:20 CST 2017
     */
    int insert(ChnlGroupViewKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_chnl_group_view
     *
     * @mbggenerated Tue Jan 10 20:02:20 CST 2017
     */
    int insertSelective(ChnlGroupViewKey record);
}