package com.stephen.core.mapper;

import com.stephen.core.model.CmsUser;

public interface CmsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_user
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_user
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    int insert(CmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_user
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    int insertSelective(CmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_user
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    CmsUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_user
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    int updateByPrimaryKeySelective(CmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_user
     *
     * @mbggenerated Wed Jan 11 10:26:46 CST 2017
     */
    int updateByPrimaryKey(CmsUser record);
}