package com.stephen.core.mapper;

import com.stephen.core.model.CommentExtWithBLOBs;

public interface CommentExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_comment_ext
     *
     * @mbggenerated Tue Jan 10 20:02:54 CST 2017
     */
    int insert(CommentExtWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_comment_ext
     *
     * @mbggenerated Tue Jan 10 20:02:54 CST 2017
     */
    int insertSelective(CommentExtWithBLOBs record);
}