package com.stephen.core.mapper;

import com.stephen.core.model.Comment;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_comment
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_comment
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_comment
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_comment
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    Comment selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_comment
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_comment
     *
     * @mbggenerated Tue Jan 10 20:02:41 CST 2017
     */
    int updateByPrimaryKey(Comment record);
}