package com.stephen.core.mapper;

import com.stephen.core.model.ContentGroupViewKey;

public interface ContentGroupViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_group_view
     *
     * @mbggenerated Tue Jan 10 20:06:13 CST 2017
     */
    int deleteByPrimaryKey(ContentGroupViewKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_group_view
     *
     * @mbggenerated Tue Jan 10 20:06:13 CST 2017
     */
    int insert(ContentGroupViewKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_group_view
     *
     * @mbggenerated Tue Jan 10 20:06:13 CST 2017
     */
    int insertSelective(ContentGroupViewKey record);
}