package com.stephen.core.mapper;

import java.util.List;

import com.stephen.core.model.ContentToChannelKey;

public interface ContentToChannelMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_content_channel
	 *
	 * @mbggenerated Fri Feb 17 15:04:06 CST 2017
	 */
	int deleteByPrimaryKey(ContentToChannelKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_content_channel
	 *
	 * @mbggenerated Fri Feb 17 15:04:06 CST 2017
	 */
	int insert(ContentToChannelKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table s_content_channel
	 *
	 * @mbggenerated Fri Feb 17 15:04:06 CST 2017
	 */
	int insertSelective(ContentToChannelKey record);

	List<ContentToChannelKey> selectContentByChannelId(Integer channelId);

	ContentToChannelKey selectChannelByContentId(Integer contentId);
}