package com.stephen.core.mapper;

import com.stephen.core.model.ContentCount;

public interface ContentCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_count
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    int deleteByPrimaryKey(Integer contentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_count
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    int insert(ContentCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_count
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    int insertSelective(ContentCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_count
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    ContentCount selectByPrimaryKey(Integer contentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_count
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    int updateByPrimaryKeySelective(ContentCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_count
     *
     * @mbggenerated Tue Jan 10 20:05:31 CST 2017
     */
    int updateByPrimaryKey(ContentCount record);
}