package com.stephen.core.mapper;

import com.stephen.core.model.ContentCheck;

public interface ContentCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_check
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    int deleteByPrimaryKey(Integer contentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_check
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    int insert(ContentCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_check
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    int insertSelective(ContentCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_check
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    ContentCheck selectByPrimaryKey(Integer contentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_check
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    int updateByPrimaryKeySelective(ContentCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_check
     *
     * @mbggenerated Tue Jan 10 20:05:15 CST 2017
     */
    int updateByPrimaryKey(ContentCheck record);
}