package com.stephen.core.mapper;

import com.stephen.core.model.ContentPicture;
import com.stephen.core.model.ContentPictureKey;

public interface ContentPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_picture
     *
     * @mbggenerated Tue Jan 10 20:06:39 CST 2017
     */
    int deleteByPrimaryKey(ContentPictureKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_picture
     *
     * @mbggenerated Tue Jan 10 20:06:39 CST 2017
     */
    int insert(ContentPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_picture
     *
     * @mbggenerated Tue Jan 10 20:06:39 CST 2017
     */
    int insertSelective(ContentPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_picture
     *
     * @mbggenerated Tue Jan 10 20:06:39 CST 2017
     */
    ContentPicture selectByPrimaryKey(ContentPictureKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_picture
     *
     * @mbggenerated Tue Jan 10 20:06:39 CST 2017
     */
    int updateByPrimaryKeySelective(ContentPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_picture
     *
     * @mbggenerated Tue Jan 10 20:06:39 CST 2017
     */
    int updateByPrimaryKey(ContentPicture record);
}