package com.stephen.core.mapper;

import com.stephen.core.model.ContentChannelKey;

public interface ContentChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_channel
     *
     * @mbggenerated Wed Feb 15 22:53:04 CST 2017
     */
    int deleteByPrimaryKey(ContentChannelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_channel
     *
     * @mbggenerated Wed Feb 15 22:53:04 CST 2017
     */
    int insert(ContentChannelKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_channel
     *
     * @mbggenerated Wed Feb 15 22:53:04 CST 2017
     */
    int insertSelective(ContentChannelKey record);
}