package com.stephen.core.mapper;

import com.stephen.core.model.ContentAttachment;

public interface ContentAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_attachment
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    int insert(ContentAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_attachment
     *
     * @mbggenerated Tue Jan 10 20:04:42 CST 2017
     */
    int insertSelective(ContentAttachment record);
}