package com.stephen.core.mapper;

import com.stephen.core.model.ContentTopicKey;

public interface ContentTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_topic
     *
     * @mbggenerated Tue Jan 10 20:06:57 CST 2017
     */
    int deleteByPrimaryKey(ContentTopicKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_topic
     *
     * @mbggenerated Tue Jan 10 20:06:57 CST 2017
     */
    int insert(ContentTopicKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_content_topic
     *
     * @mbggenerated Tue Jan 10 20:06:57 CST 2017
     */
    int insertSelective(ContentTopicKey record);
}