package com.stephen.core.mapper;

import com.stephen.core.model.Dictionary;

public interface DictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_dictionary
     *
     * @mbggenerated Wed Jan 11 10:00:27 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_dictionary
     *
     * @mbggenerated Wed Jan 11 10:00:27 CST 2017
     */
    int insert(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_dictionary
     *
     * @mbggenerated Wed Jan 11 10:00:27 CST 2017
     */
    int insertSelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_dictionary
     *
     * @mbggenerated Wed Jan 11 10:00:27 CST 2017
     */
    Dictionary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_dictionary
     *
     * @mbggenerated Wed Jan 11 10:00:27 CST 2017
     */
    int updateByPrimaryKeySelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_dictionary
     *
     * @mbggenerated Wed Jan 11 10:00:27 CST 2017
     */
    int updateByPrimaryKey(Dictionary record);
}