package com.stephen.core.mapper;

import com.stephen.core.model.File;

public interface FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_file
     *
     * @mbggenerated Wed Jan 11 10:00:54 CST 2017
     */
    int deleteByPrimaryKey(String filePath);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_file
     *
     * @mbggenerated Wed Jan 11 10:00:54 CST 2017
     */
    int insert(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_file
     *
     * @mbggenerated Wed Jan 11 10:00:54 CST 2017
     */
    int insertSelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_file
     *
     * @mbggenerated Wed Jan 11 10:00:54 CST 2017
     */
    File selectByPrimaryKey(String filePath);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_file
     *
     * @mbggenerated Wed Jan 11 10:00:54 CST 2017
     */
    int updateByPrimaryKeySelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_file
     *
     * @mbggenerated Wed Jan 11 10:00:54 CST 2017
     */
    int updateByPrimaryKey(File record);
}