package com.stephen.core.mapper;

import com.stephen.core.model.Log;

public interface LogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_log
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_log
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    int insert(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_log
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    int insertSelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_log
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    Log selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_log
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    int updateByPrimaryKeySelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_log
     *
     * @mbggenerated Wed Jan 11 10:01:39 CST 2017
     */
    int updateByPrimaryKey(Log record);
}