package com.stephen.core.mapper;

import com.stephen.core.model.Message;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message
     *
     * @mbggenerated Wed Jan 11 10:01:58 CST 2017
     */
    int deleteByPrimaryKey(Integer msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message
     *
     * @mbggenerated Wed Jan 11 10:01:58 CST 2017
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message
     *
     * @mbggenerated Wed Jan 11 10:01:58 CST 2017
     */
    int insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message
     *
     * @mbggenerated Wed Jan 11 10:01:58 CST 2017
     */
    Message selectByPrimaryKey(Integer msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message
     *
     * @mbggenerated Wed Jan 11 10:01:58 CST 2017
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message
     *
     * @mbggenerated Wed Jan 11 10:01:58 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message
     *
     * @mbggenerated Wed Jan 11 10:01:58 CST 2017
     */
    int updateByPrimaryKey(Message record);
}