package com.stephen.core.mapper;

import java.util.List;

import com.stephen.core.model.Navi;

public interface NaviMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_navi
     *
     * @mbggenerated Thu Feb 16 00:56:34 CST 2017
     */
    int deleteByPrimaryKey(Integer naviId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_navi
     *
     * @mbggenerated Thu Feb 16 00:56:34 CST 2017
     */
    int insert(Navi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_navi
     *
     * @mbggenerated Thu Feb 16 00:56:34 CST 2017
     */
    int insertSelective(Navi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_navi
     *
     * @mbggenerated Thu Feb 16 00:56:34 CST 2017
     */
    Navi selectByPrimaryKey(Integer naviId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_navi
     *
     * @mbggenerated Thu Feb 16 00:56:34 CST 2017
     */
    int updateByPrimaryKeySelective(Navi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_navi
     *
     * @mbggenerated Thu Feb 16 00:56:34 CST 2017
     */
    int updateByPrimaryKey(Navi record);

	List<Navi> selectAll();
}