package com.stephen.core.mapper;

import com.stephen.core.model.Permission;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbggenerated Wed Jan 11 10:15:54 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbggenerated Wed Jan 11 10:15:54 CST 2017
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbggenerated Wed Jan 11 10:15:54 CST 2017
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbggenerated Wed Jan 11 10:15:54 CST 2017
     */
    Permission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbggenerated Wed Jan 11 10:15:54 CST 2017
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbggenerated Wed Jan 11 10:15:54 CST 2017
     */
    int updateByPrimaryKey(Permission record);
}