package com.stephen.core.mapper;

import com.stephen.core.model.ReceiverMessage;

public interface ReceiverMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_receiver_message
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    int deleteByPrimaryKey(Integer msgReId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_receiver_message
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    int insert(ReceiverMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_receiver_message
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    int insertSelective(ReceiverMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_receiver_message
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    ReceiverMessage selectByPrimaryKey(Integer msgReId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_receiver_message
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    int updateByPrimaryKeySelective(ReceiverMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_receiver_message
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(ReceiverMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_receiver_message
     *
     * @mbggenerated Wed Jan 11 10:03:03 CST 2017
     */
    int updateByPrimaryKey(ReceiverMessage record);
}