package com.stephen.core.mapper;

import com.stephen.core.model.RolePermission;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_permission
     *
     * @mbggenerated Wed Jan 11 10:05:54 CST 2017
     */
    int insert(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_permission
     *
     * @mbggenerated Wed Jan 11 10:05:54 CST 2017
     */
    int insertSelective(RolePermission record);
}