package com.stephen.core.mapper;

import com.stephen.core.model.SiteAccessPages;

public interface SiteAccessPagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access_pages
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    int deleteByPrimaryKey(Integer accessPagesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access_pages
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    int insert(SiteAccessPages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access_pages
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    int insertSelective(SiteAccessPages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access_pages
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    SiteAccessPages selectByPrimaryKey(Integer accessPagesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access_pages
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    int updateByPrimaryKeySelective(SiteAccessPages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access_pages
     *
     * @mbggenerated Wed Jan 11 10:07:13 CST 2017
     */
    int updateByPrimaryKey(SiteAccessPages record);
}