package com.stephen.core.mapper;

import com.stephen.core.model.SiteAccessCount;

public interface SiteAccessCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access_count
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    int deleteByPrimaryKey(Integer accessCount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access_count
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    int insert(SiteAccessCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access_count
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    int insertSelective(SiteAccessCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access_count
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    SiteAccessCount selectByPrimaryKey(Integer accessCount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access_count
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    int updateByPrimaryKeySelective(SiteAccessCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access_count
     *
     * @mbggenerated Wed Jan 11 10:06:57 CST 2017
     */
    int updateByPrimaryKey(SiteAccessCount record);
}