package com.stephen.core.mapper;

import com.stephen.core.model.SiteAccess;

public interface SiteAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    int deleteByPrimaryKey(Integer accessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    int insert(SiteAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    int insertSelective(SiteAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    SiteAccess selectByPrimaryKey(Integer accessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    int updateByPrimaryKeySelective(SiteAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access
     *
     * @mbggenerated Wed Jan 11 10:06:41 CST 2017
     */
    int updateByPrimaryKey(SiteAccess record);
}