package com.stephen.core.mapper;

import com.stephen.core.model.SiteAccessStatistic;

public interface SiteAccessStatisticMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access_statistic
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    int deleteByPrimaryKey(Integer accessStatisticId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access_statistic
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    int insert(SiteAccessStatistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access_statistic
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    int insertSelective(SiteAccessStatistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access_statistic
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    SiteAccessStatistic selectByPrimaryKey(Integer accessStatisticId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access_statistic
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    int updateByPrimaryKeySelective(SiteAccessStatistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_site_access_statistic
     *
     * @mbggenerated Wed Jan 11 10:07:35 CST 2017
     */
    int updateByPrimaryKey(SiteAccessStatistic record);
}