package com.stephen.core.mapper;

import com.stephen.core.model.Topic;

public interface TopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_topic
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    int deleteByPrimaryKey(Integer topicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_topic
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    int insert(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_topic
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    int insertSelective(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_topic
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    Topic selectByPrimaryKey(Integer topicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_topic
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    int updateByPrimaryKeySelective(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_topic
     *
     * @mbggenerated Wed Jan 11 10:08:14 CST 2017
     */
    int updateByPrimaryKey(Topic record);
}