package com.stephen.core.mapper;

import com.stephen.core.model.UserMenu;

public interface UserMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_menu
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_menu
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    int insert(UserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_menu
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    int insertSelective(UserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_menu
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    UserMenu selectByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_menu
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    int updateByPrimaryKeySelective(UserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_menu
     *
     * @mbggenerated Wed Jan 11 10:10:19 CST 2017
     */
    int updateByPrimaryKey(UserMenu record);
}