package com.stephen.core.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.stephen.core.model.User;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user
	 * @mbggenerated  Sat Feb 18 19:49:53 CST 2017
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user
	 * @mbggenerated  Sat Feb 18 19:49:53 CST 2017
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user
	 * @mbggenerated  Sat Feb 18 19:49:53 CST 2017
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user
	 * @mbggenerated  Sat Feb 18 19:49:53 CST 2017
	 */
	User selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user
	 * @mbggenerated  Sat Feb 18 19:49:53 CST 2017
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user
	 * @mbggenerated  Sat Feb 18 19:49:53 CST 2017
	 */
	int updateByPrimaryKey(User record);

	int selectLastId();

	List<User> selectUsersByGroupId(@Param("groupId") Integer groupId, @Param("start") int start,
			@Param("pageSize") int pageSize);

	List<User> selectAllUsers(@Param("start") int i, @Param("pageSize") int pageSize);

	int selectCount();
}