package com.stephen.core.mapper;

import com.stephen.core.model.UserExt;

public interface UserExtMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user_ext
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user_ext
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	int insert(UserExt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user_ext
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	int insertSelective(UserExt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user_ext
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	UserExt selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user_ext
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	int updateByPrimaryKeySelective(UserExt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user_ext
	 * @mbggenerated  Thu Feb 16 11:01:32 CST 2017
	 */
	int updateByPrimaryKey(UserExt record);
}