package com.stephen.core.mapper;

import com.stephen.core.model.UserRoleKey;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbggenerated Wed Jan 11 10:10:34 CST 2017
     */
    int deleteByPrimaryKey(UserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbggenerated Wed Jan 11 10:10:34 CST 2017
     */
    int insert(UserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbggenerated Wed Jan 11 10:10:34 CST 2017
     */
    int insertSelective(UserRoleKey record);
}