package com.stephen.core.mapper;

import com.stephen.core.model.UserCollectionKey;

public interface UserCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_collection
     *
     * @mbggenerated Wed Jan 11 10:09:34 CST 2017
     */
    int deleteByPrimaryKey(UserCollectionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_collection
     *
     * @mbggenerated Wed Jan 11 10:09:34 CST 2017
     */
    int insert(UserCollectionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_collection
     *
     * @mbggenerated Wed Jan 11 10:09:34 CST 2017
     */
    int insertSelective(UserCollectionKey record);
}